# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_single.ui'
#
# Created: Thu Jun 27 22:31:45 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowSingle(object):
    def setupUi(self, MainWindowSingle):
        MainWindowSingle.setObjectName(_fromUtf8("MainWindowSingle"))
        MainWindowSingle.resize(923, 664)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowSingle.sizePolicy().hasHeightForWidth())
        MainWindowSingle.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindowSingle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mainTab = QtGui.QTabWidget(self.centralwidget)
        self.mainTab.setGeometry(QtCore.QRect(0, 40, 1091, 591))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTab.sizePolicy().hasHeightForWidth())
        self.mainTab.setSizePolicy(sizePolicy)
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.data = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setObjectName(_fromUtf8("data"))
        self.frame = QtGui.QFrame(self.data)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 131))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 57, 14))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.showInactive = QtGui.QCheckBox(self.frame)
        self.showInactive.setGeometry(QtCore.QRect(50, 10, 121, 21))
        self.showInactive.setChecked(True)
        self.showInactive.setObjectName(_fromUtf8("showInactive"))
        self.jobList = QtGui.QListWidget(self.frame)
        self.jobList.setGeometry(QtCore.QRect(10, 30, 381, 91))
        self.jobList.setObjectName(_fromUtf8("jobList"))
        self.frame_2 = QtGui.QFrame(self.data)
        self.frame_2.setGeometry(QtCore.QRect(0, 130, 431, 421))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 421, 91))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 51))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.companyname = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.companyname.setObjectName(_fromUtf8("companyname"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.companyname)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.loan = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.loan.setDecimals(2)
        self.loan.setMaximum(99999999.99)
        self.loan.setObjectName(_fromUtf8("loan"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.loan)
        self.saveCompany = QtGui.QPushButton(self.frame_4)
        self.saveCompany.setGeometry(QtCore.QRect(110, 60, 91, 23))
        self.saveCompany.setObjectName(_fromUtf8("saveCompany"))
        self.tabWidget_2 = QtGui.QTabWidget(self.frame_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 90, 421, 221))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 171, 96))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout.addWidget(self.label_25)
        self.creditList = QtGui.QListWidget(self.verticalLayoutWidget)
        self.creditList.setObjectName(_fromUtf8("creditList"))
        self.verticalLayout.addWidget(self.creditList)
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(180, 10, 213, 105))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.creditValue = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.creditValue.setDecimals(2)
        self.creditValue.setMaximum(99999.99)
        self.creditValue.setObjectName(_fromUtf8("creditValue"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.creditValue)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.creditDate = QtGui.QDateEdit(self.formLayoutWidget_3)
        self.creditDate.setCalendarPopup(True)
        self.creditDate.setObjectName(_fromUtf8("creditDate"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.creditDate)
        self.creditPayed = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.creditPayed.setObjectName(_fromUtf8("creditPayed"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.creditPayed)
        self.creditName = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.creditName.setObjectName(_fromUtf8("creditName"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.creditName)
        self.label_30 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_30)
        self.creditActive = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.creditActive.setChecked(True)
        self.creditActive.setObjectName(_fromUtf8("creditActive"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.creditActive)
        self.createCredit = QtGui.QPushButton(self.tab)
        self.createCredit.setGeometry(QtCore.QRect(0, 120, 99, 23))
        self.createCredit.setObjectName(_fromUtf8("createCredit"))
        self.saveCredit = QtGui.QPushButton(self.tab)
        self.saveCredit.setGeometry(QtCore.QRect(110, 120, 99, 23))
        self.saveCredit.setObjectName(_fromUtf8("saveCredit"))
        self.deleteCredit = QtGui.QPushButton(self.tab)
        self.deleteCredit.setGeometry(QtCore.QRect(220, 120, 99, 23))
        self.deleteCredit.setObjectName(_fromUtf8("deleteCredit"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 181, 108))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_20 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.loanSplitList = QtGui.QListWidget(self.formLayoutWidget_6)
        self.loanSplitList.setObjectName(_fromUtf8("loanSplitList"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.loanSplitList)
        self.createLoanSplit = QtGui.QPushButton(self.tab_2)
        self.createLoanSplit.setGeometry(QtCore.QRect(0, 110, 91, 23))
        self.createLoanSplit.setObjectName(_fromUtf8("createLoanSplit"))
        self.saveLoanSplit = QtGui.QPushButton(self.tab_2)
        self.saveLoanSplit.setGeometry(QtCore.QRect(90, 110, 91, 23))
        self.saveLoanSplit.setObjectName(_fromUtf8("saveLoanSplit"))
        self.deleteLoanSplit = QtGui.QPushButton(self.tab_2)
        self.deleteLoanSplit.setGeometry(QtCore.QRect(180, 110, 101, 23))
        self.deleteLoanSplit.setObjectName(_fromUtf8("deleteLoanSplit"))
        self.formLayoutWidget_8 = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(180, 0, 231, 101))
        self.formLayoutWidget_8.setObjectName(_fromUtf8("formLayoutWidget_8"))
        self.formLayout_8 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setMargin(0)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.loanSplitName = QtGui.QLineEdit(self.formLayoutWidget_8)
        self.loanSplitName.setObjectName(_fromUtf8("loanSplitName"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.loanSplitName)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.loanSplitValue = QtGui.QDoubleSpinBox(self.formLayoutWidget_8)
        self.loanSplitValue.setMaximum(9999.99)
        self.loanSplitValue.setObjectName(_fromUtf8("loanSplitValue"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.loanSplitValue)
        self.loanSplitMoney = QtGui.QCheckBox(self.formLayoutWidget_8)
        self.loanSplitMoney.setObjectName(_fromUtf8("loanSplitMoney"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.loanSplitMoney)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(210, 0, 191, 101))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.chargesName = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.chargesName.setObjectName(_fromUtf8("chargesName"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.chargesName)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.chargesValue = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.chargesValue.setObjectName(_fromUtf8("chargesValue"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.chargesValue)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.chargesList = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.chargesList.setObjectName(_fromUtf8("chargesList"))
        self.verticalLayout_2.addWidget(self.chargesList)
        self.createCharge = QtGui.QPushButton(self.tab_3)
        self.createCharge.setGeometry(QtCore.QRect(0, 110, 91, 23))
        self.createCharge.setObjectName(_fromUtf8("createCharge"))
        self.saveCharge = QtGui.QPushButton(self.tab_3)
        self.saveCharge.setGeometry(QtCore.QRect(90, 110, 81, 23))
        self.saveCharge.setObjectName(_fromUtf8("saveCharge"))
        self.deleteCharge = QtGui.QPushButton(self.tab_3)
        self.deleteCharge.setGeometry(QtCore.QRect(170, 110, 91, 23))
        self.deleteCharge.setObjectName(_fromUtf8("deleteCharge"))
        self.addChargeToJob = QtGui.QPushButton(self.tab_3)
        self.addChargeToJob.setGeometry(QtCore.QRect(269, 110, 141, 23))
        self.addChargeToJob.setObjectName(_fromUtf8("addChargeToJob"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 130, 401, 61))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.frame_6 = QtGui.QFrame(self.data)
        self.frame_6.setGeometry(QtCore.QRect(439, 0, 401, 561))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayoutWidget = QtGui.QWidget(self.frame_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 371))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.jobname = QtGui.QLineEdit(self.formLayoutWidget)
        self.jobname.setObjectName(_fromUtf8("jobname"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.jobname)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.jobplace = QtGui.QLineEdit(self.formLayoutWidget)
        self.jobplace.setObjectName(_fromUtf8("jobplace"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.jobplace)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.baustellenleiter = QtGui.QLineEdit(self.formLayoutWidget)
        self.baustellenleiter.setObjectName(_fromUtf8("baustellenleiter"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.baustellenleiter)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.hours = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.hours.setMaximum(24.0)
        self.hours.setProperty("value", 8.0)
        self.hours.setObjectName(_fromUtf8("hours"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.hours)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.correctionHours = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.correctionHours.setObjectName(_fromUtf8("correctionHours"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.correctionHours)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_11)
        self.weekendDays = QtGui.QSpinBox(self.formLayoutWidget)
        self.weekendDays.setProperty("value", 2)
        self.weekendDays.setObjectName(_fromUtf8("weekendDays"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.weekendDays)
        self.jobComment = QtGui.QPlainTextEdit(self.formLayoutWidget)
        self.jobComment.setObjectName(_fromUtf8("jobComment"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.jobComment)
        self.saveJob = QtGui.QPushButton(self.formLayoutWidget)
        self.saveJob.setObjectName(_fromUtf8("saveJob"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.saveJob)
        self.active = QtGui.QCheckBox(self.formLayoutWidget)
        self.active.setChecked(True)
        self.active.setObjectName(_fromUtf8("active"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.active)
        self.createJob = QtGui.QPushButton(self.formLayoutWidget)
        self.createJob.setEnabled(False)
        self.createJob.setObjectName(_fromUtf8("createJob"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.createJob)
        self.deleteJob = QtGui.QPushButton(self.formLayoutWidget)
        self.deleteJob.setObjectName(_fromUtf8("deleteJob"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.deleteJob)
        self.formLayoutWidget_9 = QtGui.QWidget(self.frame_6)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(20, 380, 351, 171))
        self.formLayoutWidget_9.setObjectName(_fromUtf8("formLayoutWidget_9"))
        self.formLayout_9 = QtGui.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setMargin(0)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.daysCalc = QtGui.QLabel(self.formLayoutWidget_9)
        self.daysCalc.setObjectName(_fromUtf8("daysCalc"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.daysCalc)
        self.hoursCalc = QtGui.QLabel(self.formLayoutWidget_9)
        self.hoursCalc.setObjectName(_fromUtf8("hoursCalc"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.hoursCalc)
        self.deleteWorkSpese = QtGui.QPushButton(self.formLayoutWidget_9)
        self.deleteWorkSpese.setObjectName(_fromUtf8("deleteWorkSpese"))
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.LabelRole, self.deleteWorkSpese)
        self.label_28 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_28)
        self.workChargesList = QtGui.QListWidget(self.formLayoutWidget_9)
        self.workChargesList.setObjectName(_fromUtf8("workChargesList"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.SpanningRole, self.workChargesList)
        self.wChargeSave = QtGui.QPushButton(self.formLayoutWidget_9)
        self.wChargeSave.setObjectName(_fromUtf8("wChargeSave"))
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.FieldRole, self.wChargeSave)
        self.wChargeTimes = QtGui.QSpinBox(self.formLayoutWidget_9)
        self.wChargeTimes.setObjectName(_fromUtf8("wChargeTimes"))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.FieldRole, self.wChargeTimes)
        self.label_29 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.mainTab.addTab(self.data, _fromUtf8(""))
        self.logic = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logic.sizePolicy().hasHeightForWidth())
        self.logic.setSizePolicy(sizePolicy)
        self.logic.setObjectName(_fromUtf8("logic"))
        self.viewTabs = QtGui.QTabWidget(self.logic)
        self.viewTabs.setGeometry(QtCore.QRect(0, 10, 1071, 541))
        self.viewTabs.setObjectName(_fromUtf8("viewTabs"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.frame_7 = QtGui.QFrame(self.tab_4)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 591, 151))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.frame_7)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(260, 20, 271, 82))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.filterAll = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterAll.setChecked(True)
        self.filterAll.setObjectName(_fromUtf8("filterAll"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.filterAll)
        self.filterCalendar = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterCalendar.setChecked(True)
        self.filterCalendar.setObjectName(_fromUtf8("filterCalendar"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.filterCalendar)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.infoSearch = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.infoSearch.setText(_fromUtf8(""))
        self.infoSearch.setObjectName(_fromUtf8("infoSearch"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.infoSearch)
        self.filterInactive = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterInactive.setChecked(True)
        self.filterInactive.setObjectName(_fromUtf8("filterInactive"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.filterInactive)
        self.workCalendar = QtGui.QCalendarWidget(self.frame_7)
        self.workCalendar.setGeometry(QtCore.QRect(10, 10, 221, 131))
        self.workCalendar.setObjectName(_fromUtf8("workCalendar"))
        self.graphFrame = QtGui.QFrame(self.tab_4)
        self.graphFrame.setGeometry(QtCore.QRect(590, 0, 311, 151))
        self.graphFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.graphFrame.setObjectName(_fromUtf8("graphFrame"))
        self.graphView = QtGui.QGraphicsView(self.graphFrame)
        self.graphView.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.graphView.setObjectName(_fromUtf8("graphView"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(350, 430, 261, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.kled = KLed(self.horizontalLayoutWidget)
        self.kled.setObjectName(_fromUtf8("kled"))
        self.horizontalLayout.addWidget(self.kled)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.amount = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.amount.setObjectName(_fromUtf8("amount"))
        self.horizontalLayout.addWidget(self.amount)
        self.infoExelCredits = QtGui.QTextEdit(self.tab_4)
        self.infoExelCredits.setGeometry(QtCore.QRect(20, 430, 291, 76))
        self.infoExelCredits.setReadOnly(True)
        self.infoExelCredits.setObjectName(_fromUtf8("infoExelCredits"))
        self.infoExel = QtGui.QTableWidget(self.tab_4)
        self.infoExel.setGeometry(QtCore.QRect(0, 150, 1021, 271))
        self.infoExel.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.infoExel.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.infoExel.setColumnCount(8)
        self.infoExel.setObjectName(_fromUtf8("infoExel"))
        self.infoExel.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(7, item)
        self.infoExel.horizontalHeader().setSortIndicatorShown(True)
        self.viewTabs.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.companyViewText = QtGui.QTextEdit(self.tab_5)
        self.companyViewText.setGeometry(QtCore.QRect(240, 0, 551, 511))
        self.companyViewText.setReadOnly(True)
        self.companyViewText.setObjectName(_fromUtf8("companyViewText"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 234, 197))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.companyViewCalendar = QtGui.QCalendarWidget(self.gridLayoutWidget)
        self.companyViewCalendar.setObjectName(_fromUtf8("companyViewCalendar"))
        self.gridLayout.addWidget(self.companyViewCalendar, 1, 0, 1, 1)
        self.companyViewCalendarFilter = QtGui.QCheckBox(self.gridLayoutWidget)
        self.companyViewCalendarFilter.setObjectName(_fromUtf8("companyViewCalendarFilter"))
        self.gridLayout.addWidget(self.companyViewCalendarFilter, 0, 0, 1, 1)
        self.viewTabs.addTab(self.tab_5, _fromUtf8(""))
        self.mainTab.addTab(self.logic, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.checkBox = QtGui.QCheckBox(self.tab_6)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 451, 221))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 2, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 1, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 3, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 4, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 5, 1, 1, 1)
        self.pfList = QtGui.QListWidget(self.gridLayoutWidget_2)
        self.pfList.setObjectName(_fromUtf8("pfList"))
        self.gridLayout_2.addWidget(self.pfList, 0, 0, 7, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 6, 1, 1, 1)
        self.pfName = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.pfName.setObjectName(_fromUtf8("pfName"))
        self.gridLayout_2.addWidget(self.pfName, 0, 2, 1, 1)
        self.pfValue = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.pfValue.setMaximum(9999999.99)
        self.pfValue.setObjectName(_fromUtf8("pfValue"))
        self.gridLayout_2.addWidget(self.pfValue, 1, 2, 1, 1)
        self.pfDate = QtGui.QDateEdit(self.gridLayoutWidget_2)
        self.pfDate.setCalendarPopup(True)
        self.pfDate.setObjectName(_fromUtf8("pfDate"))
        self.gridLayout_2.addWidget(self.pfDate, 2, 2, 1, 1)
        self.pfRepeat = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.pfRepeat.setObjectName(_fromUtf8("pfRepeat"))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pfRepeat, 3, 2, 1, 2)
        self.pfActive = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.pfActive.setText(_fromUtf8(""))
        self.pfActive.setChecked(True)
        self.pfActive.setObjectName(_fromUtf8("pfActive"))
        self.gridLayout_2.addWidget(self.pfActive, 6, 2, 1, 1)
        self.pfPlusMinus = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.pfPlusMinus.setObjectName(_fromUtf8("pfPlusMinus"))
        self.pfPlusMinus.addItem(_fromUtf8(""))
        self.pfPlusMinus.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pfPlusMinus, 5, 2, 1, 1)
        self.pfRepeatTimes = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.pfRepeatTimes.setObjectName(_fromUtf8("pfRepeatTimes"))
        self.gridLayout_2.addWidget(self.pfRepeatTimes, 4, 2, 1, 1)
        self.pfCreate = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pfCreate.setObjectName(_fromUtf8("pfCreate"))
        self.gridLayout_2.addWidget(self.pfCreate, 7, 0, 1, 1)
        self.pfSave = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pfSave.setObjectName(_fromUtf8("pfSave"))
        self.gridLayout_2.addWidget(self.pfSave, 7, 1, 1, 1)
        self.pfDelete = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pfDelete.setObjectName(_fromUtf8("pfDelete"))
        self.gridLayout_2.addWidget(self.pfDelete, 7, 2, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(460, 30, 461, 201))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 0, 1, 1, 1)
        self.pfSearch = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.pfSearch.setObjectName(_fromUtf8("pfSearch"))
        self.gridLayout_3.addWidget(self.pfSearch, 0, 3, 1, 1)
        self.pfCalendarEnabled = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.pfCalendarEnabled.setObjectName(_fromUtf8("pfCalendarEnabled"))
        self.gridLayout_3.addWidget(self.pfCalendarEnabled, 2, 0, 1, 1)
        self.pfSearchEnabled = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.pfSearchEnabled.setText(_fromUtf8(""))
        self.pfSearchEnabled.setObjectName(_fromUtf8("pfSearchEnabled"))
        self.gridLayout_3.addWidget(self.pfSearchEnabled, 0, 4, 1, 1)
        self.pfCalendar = QtGui.QCalendarWidget(self.gridLayoutWidget_3)
        self.pfCalendar.setObjectName(_fromUtf8("pfCalendar"))
        self.gridLayout_3.addWidget(self.pfCalendar, 0, 0, 1, 1)
        self.pfSummary = QtGui.QTextEdit(self.tab_6)
        self.pfSummary.setGeometry(QtCore.QRect(20, 260, 671, 331))
        self.pfSummary.setObjectName(_fromUtf8("pfSummary"))
        self.mainTab.addTab(self.tab_6, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.settings)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 291, 251))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_23 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.configList = QtGui.QListWidget(self.formLayoutWidget_7)
        self.configList.setObjectName(_fromUtf8("configList"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.SpanningRole, self.configList)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_27)
        self.configKey = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.configKey.setObjectName(_fromUtf8("configKey"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.configKey)
        self.configValue = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.configValue.setObjectName(_fromUtf8("configValue"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.configValue)
        self.createConfig = QtGui.QPushButton(self.formLayoutWidget_7)
        self.createConfig.setObjectName(_fromUtf8("createConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.createConfig)
        self.saveConfig = QtGui.QPushButton(self.formLayoutWidget_7)
        self.saveConfig.setObjectName(_fromUtf8("saveConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.saveConfig)
        self.deleteConfig = QtGui.QPushButton(self.formLayoutWidget_7)
        self.deleteConfig.setObjectName(_fromUtf8("deleteConfig"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.FieldRole, self.deleteConfig)
        self.textEdit = QtGui.QTextEdit(self.settings)
        self.textEdit.setGeometry(QtCore.QRect(330, 10, 421, 261))
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.mainTab.addTab(self.settings, _fromUtf8(""))
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(760, 10, 271, 16))
        self.status.setTextFormat(QtCore.Qt.PlainText)
        self.status.setObjectName(_fromUtf8("status"))
        MainWindowSingle.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindowSingle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindowSingle.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowSingle)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowSingle.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowSingle)
        self.mainTab.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        self.viewTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowSingle)

    def retranslateUi(self, MainWindowSingle):
        MainWindowSingle.setWindowTitle(_translate("MainWindowSingle", "Jobmanagement - Single View", None))
        self.mainTab.setWhatsThis(_translate("MainWindowSingle", "<html><head/><body><p>Personal finances</p></body></html>", None))
        self.label_2.setText(_translate("MainWindowSingle", "Jobs", None))
        self.showInactive.setText(_translate("MainWindowSingle", "Show Inactive", None))
        self.label_3.setText(_translate("MainWindowSingle", "Companyname", None))
        self.label_4.setText(_translate("MainWindowSingle", "Loan", None))
        self.saveCompany.setText(_translate("MainWindowSingle", "Save", None))
        self.label_25.setText(_translate("MainWindowSingle", "Credits (to Company)", None))
        self.label_15.setText(_translate("MainWindowSingle", "Money", None))
        self.label_16.setText(_translate("MainWindowSingle", "Date", None))
        self.creditDate.setDisplayFormat(_translate("MainWindowSingle", "dd.MM.yyyy", None))
        self.creditPayed.setText(_translate("MainWindowSingle", "Payed", None))
        self.label_30.setText(_translate("MainWindowSingle", "Name/Comment", None))
        self.creditActive.setText(_translate("MainWindowSingle", "Active", None))
        self.createCredit.setText(_translate("MainWindowSingle", "Create", None))
        self.saveCredit.setText(_translate("MainWindowSingle", "Save", None))
        self.deleteCredit.setText(_translate("MainWindowSingle", "Delete", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindowSingle", "Credits", None))
        self.label_20.setText(_translate("MainWindowSingle", "Loan Splits", None))
        self.createLoanSplit.setText(_translate("MainWindowSingle", "Create", None))
        self.saveLoanSplit.setText(_translate("MainWindowSingle", "Save", None))
        self.deleteLoanSplit.setText(_translate("MainWindowSingle", "Delete", None))
        self.label_21.setText(_translate("MainWindowSingle", "Name", None))
        self.label_22.setText(_translate("MainWindowSingle", "Value", None))
        self.loanSplitMoney.setText(_translate("MainWindowSingle", "on=money,off=percent", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindowSingle", "Loan Splits", None))
        self.label_17.setText(_translate("MainWindowSingle", "Name", None))
        self.label_18.setText(_translate("MainWindowSingle", "Money", None))
        self.label_8.setText(_translate("MainWindowSingle", "Static Charges", None))
        self.createCharge.setText(_translate("MainWindowSingle", "Create", None))
        self.saveCharge.setText(_translate("MainWindowSingle", "Save", None))
        self.deleteCharge.setText(_translate("MainWindowSingle", "Delete", None))
        self.addChargeToJob.setText(_translate("MainWindowSingle", "Add to job", None))
        self.plainTextEdit.setPlainText(_translate("MainWindowSingle", "A static charge doesn\'t get active till you add it to a job. Don\'t forget to tell the job, how many time u used the charge effective..", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindowSingle", "Static Charges", None))
        self.label_5.setText(_translate("MainWindowSingle", "Jobname", None))
        self.label_6.setText(_translate("MainWindowSingle", "Place", None))
        self.label_7.setText(_translate("MainWindowSingle", "Leader", None))
        self.label_9.setText(_translate("MainWindowSingle", "Hours (per day)", None))
        self.label_12.setText(_translate("MainWindowSingle", "Correction (allTime)", None))
        self.label_11.setText(_translate("MainWindowSingle", "Weekenddays (per 7d)", None))
        self.jobComment.setPlainText(_translate("MainWindowSingle", "Comments...", None))
        self.saveJob.setText(_translate("MainWindowSingle", "Save", None))
        self.active.setText(_translate("MainWindowSingle", "Active", None))
        self.createJob.setText(_translate("MainWindowSingle", "Create", None))
        self.deleteJob.setText(_translate("MainWindowSingle", "Delete", None))
        self.daysCalc.setText(_translate("MainWindowSingle", "how many days..", None))
        self.hoursCalc.setText(_translate("MainWindowSingle", "how many hours @all..", None))
        self.deleteWorkSpese.setText(_translate("MainWindowSingle", "Delete", None))
        self.label_28.setText(_translate("MainWindowSingle", "Workchargetime (0=daily)", None))
        self.wChargeSave.setText(_translate("MainWindowSingle", "Save", None))
        self.label_29.setText(_translate("MainWindowSingle", "Workcharge", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.data), _translate("MainWindowSingle", "Data", None))
        self.mainTab.setTabToolTip(self.mainTab.indexOf(self.data), _translate("MainWindowSingle", "Here u could put in ur stuff", None))
        self.filterAll.setText(_translate("MainWindowSingle", " Filter @All", None))
        self.filterCalendar.setText(_translate("MainWindowSingle", "Filter Calendar", None))
        self.label_19.setText(_translate("MainWindowSingle", "Search", None))
        self.filterInactive.setText(_translate("MainWindowSingle", "Show Inactive", None))
        self.label_10.setText(_translate("MainWindowSingle", "Summe (gesammt)", None))
        self.infoExel.setSortingEnabled(True)
        item = self.infoExel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowSingle", "Jobname", None))
        item = self.infoExel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowSingle", "Place", None))
        item = self.infoExel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowSingle", "Leader", None))
        item = self.infoExel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowSingle", "Loan", None))
        item = self.infoExel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowSingle", "Time", None))
        item = self.infoExel.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowSingle", "Charges", None))
        item = self.infoExel.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowSingle", "Splits", None))
        item = self.infoExel.horizontalHeaderItem(7)
        item.setText(_translate("MainWindowSingle", "Summe", None))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_4), _translate("MainWindowSingle", "Overview", None))
        self.companyViewCalendarFilter.setText(_translate("MainWindowSingle", "Calendarfilter", None))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_5), _translate("MainWindowSingle", "Detailview Company", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.logic), _translate("MainWindowSingle", "Logics - Checks", None))
        self.checkBox.setText(_translate("MainWindowSingle", "Zeige Inaktive", None))
        self.label_33.setText(_translate("MainWindowSingle", "Date", None))
        self.label_31.setText(_translate("MainWindowSingle", "Value", None))
        self.label_37.setText(_translate("MainWindowSingle", "Repeat", None))
        self.label_38.setText(_translate("MainWindowSingle", "Repeat Times", None))
        self.label_32.setText(_translate("MainWindowSingle", "Name", None))
        self.label_34.setText(_translate("MainWindowSingle", "Plus/Minus", None))
        self.label_36.setText(_translate("MainWindowSingle", "Active", None))
        self.pfDate.setDisplayFormat(_translate("MainWindowSingle", "dd.MM.yyyy", None))
        self.pfRepeat.setItemText(0, _translate("MainWindowSingle", "Daily", None))
        self.pfRepeat.setItemText(1, _translate("MainWindowSingle", "Weekly", None))
        self.pfRepeat.setItemText(2, _translate("MainWindowSingle", "Monthly", None))
        self.pfPlusMinus.setItemText(0, _translate("MainWindowSingle", "+", None))
        self.pfPlusMinus.setItemText(1, _translate("MainWindowSingle", "-", None))
        self.pfCreate.setText(_translate("MainWindowSingle", "Create", None))
        self.pfSave.setText(_translate("MainWindowSingle", "Save", None))
        self.pfDelete.setText(_translate("MainWindowSingle", "Delete", None))
        self.label_39.setText(_translate("MainWindowSingle", "Search", None))
        self.pfCalendarEnabled.setText(_translate("MainWindowSingle", "Filter Calendar", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_6), _translate("MainWindowSingle", "Personal finances", None))
        self.label_23.setText(_translate("MainWindowSingle", "Configs", None))
        self.label_26.setText(_translate("MainWindowSingle", "Key", None))
        self.label_27.setText(_translate("MainWindowSingle", "Value", None))
        self.createConfig.setText(_translate("MainWindowSingle", "Create", None))
        self.saveConfig.setText(_translate("MainWindowSingle", "Save", None))
        self.deleteConfig.setText(_translate("MainWindowSingle", "Delete", None))
        self.textEdit.setHtml(_translate("MainWindowSingle", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; text-decoration: underline;\">Avaible Config-Keys</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">lang / language = language - put the right filename (*.qm in your folder) there and restart</p></body></html>", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.settings), _translate("MainWindowSingle", "Settings", "en"))
        self.status.setText(_translate("MainWindowSingle", "Status..", None))

from PyKDE4.kdeui import KLed
