# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue May 28 21:44:05 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1096, 654)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 1071, 591))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.data = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setObjectName(_fromUtf8("data"))
        self.frame = QtGui.QFrame(self.data)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 131))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.companyList = QtGui.QListWidget(self.frame)
        self.companyList.setGeometry(QtCore.QRect(0, 30, 191, 91))
        self.companyList.setObjectName(_fromUtf8("companyList"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 57, 14))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.showInactive = QtGui.QCheckBox(self.frame)
        self.showInactive.setGeometry(QtCore.QRect(270, 10, 121, 21))
        self.showInactive.setChecked(True)
        self.showInactive.setObjectName(_fromUtf8("showInactive"))
        self.jobList = QtGui.QListWidget(self.frame)
        self.jobList.setGeometry(QtCore.QRect(190, 30, 201, 91))
        self.jobList.setObjectName(_fromUtf8("jobList"))
        self.frame_2 = QtGui.QFrame(self.data)
        self.frame_2.setGeometry(QtCore.QRect(0, 130, 431, 421))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 431, 201))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.frame_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 157))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.companyname = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.companyname.setObjectName(_fromUtf8("companyname"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.companyname)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.loan = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.loan.setDecimals(2)
        self.loan.setMaximum(99999999.99)
        self.loan.setObjectName(_fromUtf8("loan"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.loan)
        self.companydescription = QtGui.QTextEdit(self.formLayoutWidget_2)
        self.companydescription.setObjectName(_fromUtf8("companydescription"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.companydescription)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_24)
        self.perHours = QtGui.QDoubleSpinBox(self.formLayoutWidget_2)
        self.perHours.setDecimals(2)
        self.perHours.setMaximum(99999999.99)
        self.perHours.setProperty("value", 1.0)
        self.perHours.setObjectName(_fromUtf8("perHours"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.perHours)
        self.createCompany = QtGui.QPushButton(self.frame_4)
        self.createCompany.setGeometry(QtCore.QRect(70, 170, 61, 23))
        self.createCompany.setObjectName(_fromUtf8("createCompany"))
        self.saveCompany = QtGui.QPushButton(self.frame_4)
        self.saveCompany.setGeometry(QtCore.QRect(10, 170, 51, 23))
        self.saveCompany.setObjectName(_fromUtf8("saveCompany"))
        self.deleteCompany = QtGui.QPushButton(self.frame_4)
        self.deleteCompany.setGeometry(QtCore.QRect(170, 170, 51, 23))
        self.deleteCompany.setObjectName(_fromUtf8("deleteCompany"))
        self.tabWidget_2 = QtGui.QTabWidget(self.frame_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 200, 421, 221))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 171, 96))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout.addWidget(self.label_25)
        self.creditList = QtGui.QListWidget(self.verticalLayoutWidget)
        self.creditList.setObjectName(_fromUtf8("creditList"))
        self.verticalLayout.addWidget(self.creditList)
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(180, 10, 181, 91))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.creditValue = QtGui.QDoubleSpinBox(self.formLayoutWidget_3)
        self.creditValue.setDecimals(2)
        self.creditValue.setMaximum(99999.99)
        self.creditValue.setObjectName(_fromUtf8("creditValue"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.creditValue)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.creditDate = QtGui.QDateEdit(self.formLayoutWidget_3)
        self.creditDate.setCalendarPopup(True)
        self.creditDate.setObjectName(_fromUtf8("creditDate"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.creditDate)
        self.creditPayed = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.creditPayed.setObjectName(_fromUtf8("creditPayed"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.creditPayed)
        self.createCredit = QtGui.QPushButton(self.tab)
        self.createCredit.setGeometry(QtCore.QRect(10, 110, 99, 23))
        self.createCredit.setObjectName(_fromUtf8("createCredit"))
        self.saveCredit = QtGui.QPushButton(self.tab)
        self.saveCredit.setGeometry(QtCore.QRect(170, 110, 99, 23))
        self.saveCredit.setObjectName(_fromUtf8("saveCredit"))
        self.deleteCredit = QtGui.QPushButton(self.tab)
        self.deleteCredit.setGeometry(QtCore.QRect(310, 110, 99, 23))
        self.deleteCredit.setObjectName(_fromUtf8("deleteCredit"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 0, 241, 181))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_20 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_22)
        self.loanSplitName = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.loanSplitName.setObjectName(_fromUtf8("loanSplitName"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.loanSplitName)
        self.loanSplitValue = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.loanSplitValue.setObjectName(_fromUtf8("loanSplitValue"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.loanSplitValue)
        self.loanSplitMoney = QtGui.QCheckBox(self.formLayoutWidget_6)
        self.loanSplitMoney.setObjectName(_fromUtf8("loanSplitMoney"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.SpanningRole, self.loanSplitMoney)
        self.loanSplitList = QtGui.QListWidget(self.formLayoutWidget_6)
        self.loanSplitList.setObjectName(_fromUtf8("loanSplitList"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.loanSplitList)
        self.createLoanSplit = QtGui.QPushButton(self.tab_2)
        self.createLoanSplit.setGeometry(QtCore.QRect(260, 10, 121, 23))
        self.createLoanSplit.setObjectName(_fromUtf8("createLoanSplit"))
        self.saveLoanSplit = QtGui.QPushButton(self.tab_2)
        self.saveLoanSplit.setGeometry(QtCore.QRect(260, 50, 99, 23))
        self.saveLoanSplit.setObjectName(_fromUtf8("saveLoanSplit"))
        self.deleteLoanSplit = QtGui.QPushButton(self.tab_2)
        self.deleteLoanSplit.setGeometry(QtCore.QRect(260, 80, 111, 23))
        self.deleteLoanSplit.setObjectName(_fromUtf8("deleteLoanSplit"))
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(200, 0, 191, 104))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.speseName = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.speseName.setObjectName(_fromUtf8("speseName"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.speseName)
        self.speseValue = QtGui.QDoubleSpinBox(self.formLayoutWidget_4)
        self.speseValue.setObjectName(_fromUtf8("speseValue"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.speseValue)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.createCharge = QtGui.QPushButton(self.formLayoutWidget_4)
        self.createCharge.setObjectName(_fromUtf8("createCharge"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.createCharge)
        self.saveCharge = QtGui.QPushButton(self.formLayoutWidget_4)
        self.saveCharge.setObjectName(_fromUtf8("saveCharge"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.saveCharge)
        self.deleteCharge = QtGui.QPushButton(self.formLayoutWidget_4)
        self.deleteCharge.setObjectName(_fromUtf8("deleteCharge"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.deleteCharge)
        self.addChargeToJob = QtGui.QPushButton(self.formLayoutWidget_4)
        self.addChargeToJob.setObjectName(_fromUtf8("addChargeToJob"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.addChargeToJob)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 201, 111))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.chargesList = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.chargesList.setObjectName(_fromUtf8("chargesList"))
        self.verticalLayout_2.addWidget(self.chargesList)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.frame_6 = QtGui.QFrame(self.data)
        self.frame_6.setGeometry(QtCore.QRect(439, 0, 401, 531))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayoutWidget = QtGui.QWidget(self.frame_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 361, 371))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.jobname = QtGui.QLineEdit(self.formLayoutWidget)
        self.jobname.setObjectName(_fromUtf8("jobname"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.jobname)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.jobplace = QtGui.QLineEdit(self.formLayoutWidget)
        self.jobplace.setObjectName(_fromUtf8("jobplace"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.jobplace)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.baustellenleiter = QtGui.QLineEdit(self.formLayoutWidget)
        self.baustellenleiter.setObjectName(_fromUtf8("baustellenleiter"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.baustellenleiter)
        self.startdate = QtGui.QDateEdit(self.formLayoutWidget)
        self.startdate.setCalendarPopup(True)
        self.startdate.setObjectName(_fromUtf8("startdate"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.startdate)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.enddate = QtGui.QDateEdit(self.formLayoutWidget)
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName(_fromUtf8("enddate"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.enddate)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.hours = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.hours.setMaximum(24.0)
        self.hours.setProperty("value", 8.0)
        self.hours.setObjectName(_fromUtf8("hours"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.hours)
        self.correctionHours = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.correctionHours.setObjectName(_fromUtf8("correctionHours"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.correctionHours)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_11)
        self.weekendDays = QtGui.QSpinBox(self.formLayoutWidget)
        self.weekendDays.setProperty("value", 2)
        self.weekendDays.setObjectName(_fromUtf8("weekendDays"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.weekendDays)
        self.createJob = QtGui.QPushButton(self.formLayoutWidget)
        self.createJob.setEnabled(False)
        self.createJob.setObjectName(_fromUtf8("createJob"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.createJob)
        self.deleteJob = QtGui.QPushButton(self.formLayoutWidget)
        self.deleteJob.setObjectName(_fromUtf8("deleteJob"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.deleteJob)
        self.saveJob = QtGui.QPushButton(self.formLayoutWidget)
        self.saveJob.setObjectName(_fromUtf8("saveJob"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.saveJob)
        self.active = QtGui.QCheckBox(self.formLayoutWidget)
        self.active.setChecked(True)
        self.active.setObjectName(_fromUtf8("active"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.active)
        self.jobComment = QtGui.QPlainTextEdit(self.formLayoutWidget)
        self.jobComment.setObjectName(_fromUtf8("jobComment"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.jobComment)
        self.daysCalc = QtGui.QLabel(self.frame_6)
        self.daysCalc.setGeometry(QtCore.QRect(230, 390, 101, 16))
        self.daysCalc.setObjectName(_fromUtf8("daysCalc"))
        self.hoursCalc = QtGui.QLabel(self.frame_6)
        self.hoursCalc.setGeometry(QtCore.QRect(190, 410, 141, 16))
        self.hoursCalc.setObjectName(_fromUtf8("hoursCalc"))
        self.workChargesList = QtGui.QListWidget(self.frame_6)
        self.workChargesList.setGeometry(QtCore.QRect(20, 390, 161, 61))
        self.workChargesList.setObjectName(_fromUtf8("workChargesList"))
        self.deleteWorkSpese = QtGui.QPushButton(self.frame_6)
        self.deleteWorkSpese.setGeometry(QtCore.QRect(20, 450, 151, 23))
        self.deleteWorkSpese.setObjectName(_fromUtf8("deleteWorkSpese"))
        self.tabWidget.addTab(self.data, _fromUtf8(""))
        self.logic = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logic.sizePolicy().hasHeightForWidth())
        self.logic.setSizePolicy(sizePolicy)
        self.logic.setObjectName(_fromUtf8("logic"))
        self.infoExel = QtGui.QTableWidget(self.logic)
        self.infoExel.setGeometry(QtCore.QRect(10, 160, 1041, 271))
        self.infoExel.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.infoExel.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.infoExel.setColumnCount(10)
        self.infoExel.setObjectName(_fromUtf8("infoExel"))
        self.infoExel.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(9, item)
        self.horizontalLayoutWidget = QtGui.QWidget(self.logic)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 440, 271, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.kled = KLed(self.horizontalLayoutWidget)
        self.kled.setObjectName(_fromUtf8("kled"))
        self.horizontalLayout.addWidget(self.kled)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.amount = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.amount.setObjectName(_fromUtf8("amount"))
        self.horizontalLayout.addWidget(self.amount)
        self.frame_7 = QtGui.QFrame(self.logic)
        self.frame_7.setGeometry(QtCore.QRect(10, 0, 591, 151))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.frame_7)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(260, 20, 271, 82))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.filterAll = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterAll.setChecked(True)
        self.filterAll.setObjectName(_fromUtf8("filterAll"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.filterAll)
        self.filterCalendar = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterCalendar.setChecked(True)
        self.filterCalendar.setObjectName(_fromUtf8("filterCalendar"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.filterCalendar)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.infoSearch = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.infoSearch.setText(_fromUtf8(""))
        self.infoSearch.setObjectName(_fromUtf8("infoSearch"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.infoSearch)
        self.filterInactive = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.filterInactive.setChecked(True)
        self.filterInactive.setObjectName(_fromUtf8("filterInactive"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.filterInactive)
        self.workCalendar = QtGui.QCalendarWidget(self.frame_7)
        self.workCalendar.setGeometry(QtCore.QRect(10, 10, 221, 131))
        self.workCalendar.setObjectName(_fromUtf8("workCalendar"))
        self.graphFrame = QtGui.QFrame(self.logic)
        self.graphFrame.setGeometry(QtCore.QRect(620, 0, 311, 151))
        self.graphFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.graphFrame.setObjectName(_fromUtf8("graphFrame"))
        self.graphView = QtGui.QGraphicsView(self.graphFrame)
        self.graphView.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.graphView.setObjectName(_fromUtf8("graphView"))
        self.tabWidget.addTab(self.logic, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.loanModelMinH = QtGui.QLineEdit(self.settings)
        self.loanModelMinH.setGeometry(QtCore.QRect(20, 120, 113, 22))
        self.loanModelMinH.setObjectName(_fromUtf8("loanModelMinH"))
        self.loanModelMaxH = QtGui.QLineEdit(self.settings)
        self.loanModelMaxH.setGeometry(QtCore.QRect(20, 150, 113, 22))
        self.loanModelMaxH.setObjectName(_fromUtf8("loanModelMaxH"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.settings)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(189, 70, 201, 161))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.loanModelName = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.loanModelName.setObjectName(_fromUtf8("loanModelName"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.loanModelName)
        self.loanModelList = QtGui.QListWidget(self.formLayoutWidget_7)
        self.loanModelList.setObjectName(_fromUtf8("loanModelList"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.loanModelList)
        self.label_23 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_23)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(760, 10, 121, 16))
        self.status.setTextFormat(QtCore.Qt.PlainText)
        self.status.setObjectName(_fromUtf8("status"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Companys", None))
        self.label_2.setText(_translate("MainWindow", "Jobs", None))
        self.showInactive.setText(_translate("MainWindow", "Show Inactive", None))
        self.label_3.setText(_translate("MainWindow", "Companyname", None))
        self.label_4.setText(_translate("MainWindow", "Loan", None))
        self.label_24.setText(_translate("MainWindow", "Per Hours", None))
        self.createCompany.setText(_translate("MainWindow", "Create", None))
        self.saveCompany.setText(_translate("MainWindow", "Save", None))
        self.deleteCompany.setText(_translate("MainWindow", "Delete", None))
        self.label_25.setText(_translate("MainWindow", "Credits (to Company)", None))
        self.label_15.setText(_translate("MainWindow", "Money", None))
        self.label_16.setText(_translate("MainWindow", "Date", None))
        self.creditDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.creditPayed.setText(_translate("MainWindow", "Payed", None))
        self.createCredit.setText(_translate("MainWindow", "Create", None))
        self.saveCredit.setText(_translate("MainWindow", "Save", None))
        self.deleteCredit.setText(_translate("MainWindow", "Delete", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Credits", None))
        self.label_20.setText(_translate("MainWindow", "Loan Splits", None))
        self.label_21.setText(_translate("MainWindow", "Name", None))
        self.label_22.setText(_translate("MainWindow", "Value", None))
        self.loanSplitMoney.setText(_translate("MainWindow", "on=money,off=percent", None))
        self.createLoanSplit.setText(_translate("MainWindow", "Create loanSplit", None))
        self.saveLoanSplit.setText(_translate("MainWindow", "Save LoanSplit", None))
        self.deleteLoanSplit.setText(_translate("MainWindow", "Delete Loansplit", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Loan Splits", None))
        self.label_17.setText(_translate("MainWindow", "Name", None))
        self.label_18.setText(_translate("MainWindow", "Money", None))
        self.createCharge.setText(_translate("MainWindow", "Create", None))
        self.saveCharge.setText(_translate("MainWindow", "Save", None))
        self.deleteCharge.setText(_translate("MainWindow", "Delete", None))
        self.addChargeToJob.setText(_translate("MainWindow", "Add to job", None))
        self.label_8.setText(_translate("MainWindow", "Static Charges", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Static Charges", None))
        self.label_5.setText(_translate("MainWindow", "Jobname", None))
        self.label_6.setText(_translate("MainWindow", "Place", None))
        self.label_7.setText(_translate("MainWindow", "Baustellenleiter", None))
        self.startdate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_13.setText(_translate("MainWindow", "Startdate", None))
        self.label_14.setText(_translate("MainWindow", "Enddate", None))
        self.enddate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_9.setText(_translate("MainWindow", "Hours (per day)", None))
        self.label_12.setText(_translate("MainWindow", "Correction (allTime)", None))
        self.label_11.setText(_translate("MainWindow", "Weekenddays (per 7d)", None))
        self.createJob.setText(_translate("MainWindow", "Create", None))
        self.deleteJob.setText(_translate("MainWindow", "Delete", None))
        self.saveJob.setText(_translate("MainWindow", "Save", None))
        self.active.setText(_translate("MainWindow", "Active", None))
        self.jobComment.setPlainText(_translate("MainWindow", "Comments...", None))
        self.daysCalc.setText(_translate("MainWindow", "how many days..", None))
        self.hoursCalc.setText(_translate("MainWindow", "how many hours @all..", None))
        self.deleteWorkSpese.setText(_translate("MainWindow", "Delete WorkSpese", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data), _translate("MainWindow", "Data", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.data), _translate("MainWindow", "Here u could put in ur stuff", None))
        item = self.infoExel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Firmenname", None))
        item = self.infoExel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jobname", None))
        item = self.infoExel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ort", None))
        item = self.infoExel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Leitung", None))
        item = self.infoExel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Lohn", None))
        item = self.infoExel.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Zeit (ges)", None))
        item = self.infoExel.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Std", None))
        item = self.infoExel.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Min", None))
        item = self.infoExel.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Spesen", None))
        item = self.infoExel.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Summe", None))
        self.label_10.setText(_translate("MainWindow", "Summe (gesammt)", None))
        self.filterAll.setText(_translate("MainWindow", " Filter @All", None))
        self.filterCalendar.setText(_translate("MainWindow", "Filter Calendar", None))
        self.label_19.setText(_translate("MainWindow", "Search", None))
        self.filterInactive.setText(_translate("MainWindow", "Show Inactive", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logic), _translate("MainWindow", "Logics - Checks", None))
        self.label_23.setText(_translate("MainWindow", "Loanmodels", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Settings", "en"))
        self.status.setText(_translate("MainWindow", "Status..", None))

from PyKDE4.kdeui import KLed
