######################################################################
# Automatically generated by qmake (3.0) Sa. Mär. 29 15:38:00 2014
######################################################################

TEMPLATE = app
TARGET = ts
INCLUDEPATH += . ./lib


# Input
SOURCES += lib/guiController.py \
          lib/staticTools.py \
          lib/models.py \
          lib/cryptClass.py
FORMS += ui/gui.ui \
	 ui/gui_single.ui
TRANSLATIONS += lang/de.ts lang/en.ts
