# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Wed Jul 30 21:31:42 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1043, 783)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mainTab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTab.sizePolicy().hasHeightForWidth())
        self.mainTab.setSizePolicy(sizePolicy)
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.data = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setObjectName(_fromUtf8("data"))
        self.gridLayout_8 = QtGui.QGridLayout(self.data)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.data)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label = QtGui.QLabel(self.tab_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.companyList = QtGui.QListWidget(self.tab_7)
        self.companyList.setObjectName(_fromUtf8("companyList"))
        self.gridLayout_7.addWidget(self.companyList, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.showInactive = QtGui.QCheckBox(self.tab_7)
        self.showInactive.setChecked(True)
        self.showInactive.setObjectName(_fromUtf8("showInactive"))
        self.gridLayout_7.addWidget(self.showInactive, 0, 2, 1, 1)
        self.jobList = QtGui.QListWidget(self.tab_7)
        self.jobList.setObjectName(_fromUtf8("jobList"))
        self.gridLayout_7.addWidget(self.jobList, 1, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.tab_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.jobname = QtGui.QLineEdit(self.tab_7)
        self.jobname.setObjectName(_fromUtf8("jobname"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.jobname)
        self.label_6 = QtGui.QLabel(self.tab_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.jobplace = QtGui.QLineEdit(self.tab_7)
        self.jobplace.setObjectName(_fromUtf8("jobplace"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.jobplace)
        self.label_7 = QtGui.QLabel(self.tab_7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.baustellenleiter = QtGui.QLineEdit(self.tab_7)
        self.baustellenleiter.setObjectName(_fromUtf8("baustellenleiter"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.baustellenleiter)
        self.label_13 = QtGui.QLabel(self.tab_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.startdate = QtGui.QDateEdit(self.tab_7)
        self.startdate.setCalendarPopup(True)
        self.startdate.setObjectName(_fromUtf8("startdate"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.startdate)
        self.label_14 = QtGui.QLabel(self.tab_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.enddate = QtGui.QDateEdit(self.tab_7)
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName(_fromUtf8("enddate"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.enddate)
        self.label_9 = QtGui.QLabel(self.tab_7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.hours = QtGui.QDoubleSpinBox(self.tab_7)
        self.hours.setMaximum(24.0)
        self.hours.setProperty("value", 8.0)
        self.hours.setObjectName(_fromUtf8("hours"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.hours)
        self.label_12 = QtGui.QLabel(self.tab_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_12)
        self.correctionHours = QtGui.QDoubleSpinBox(self.tab_7)
        self.correctionHours.setObjectName(_fromUtf8("correctionHours"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.correctionHours)
        self.label_11 = QtGui.QLabel(self.tab_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_11)
        self.weekendDays = QtGui.QSpinBox(self.tab_7)
        self.weekendDays.setProperty("value", 2)
        self.weekendDays.setObjectName(_fromUtf8("weekendDays"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.weekendDays)
        self.jobComment = QtGui.QPlainTextEdit(self.tab_7)
        self.jobComment.setObjectName(_fromUtf8("jobComment"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.jobComment)
        self.active = QtGui.QCheckBox(self.tab_7)
        self.active.setChecked(True)
        self.active.setObjectName(_fromUtf8("active"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.active)
        self.deleteJob = QtGui.QPushButton(self.tab_7)
        self.deleteJob.setObjectName(_fromUtf8("deleteJob"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.deleteJob)
        self.saveJob = QtGui.QPushButton(self.tab_7)
        self.saveJob.setObjectName(_fromUtf8("saveJob"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.saveJob)
        self.createJob = QtGui.QPushButton(self.tab_7)
        self.createJob.setEnabled(False)
        self.createJob.setObjectName(_fromUtf8("createJob"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.createJob)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.formLayout_9 = QtGui.QFormLayout()
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.daysCalc = QtGui.QLabel(self.tab_7)
        self.daysCalc.setObjectName(_fromUtf8("daysCalc"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.daysCalc)
        self.hoursCalc = QtGui.QLabel(self.tab_7)
        self.hoursCalc.setObjectName(_fromUtf8("hoursCalc"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.hoursCalc)
        self.deleteWorkSpese = QtGui.QPushButton(self.tab_7)
        self.deleteWorkSpese.setObjectName(_fromUtf8("deleteWorkSpese"))
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.LabelRole, self.deleteWorkSpese)
        self.label_28 = QtGui.QLabel(self.tab_7)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_28)
        self.workChargesList = QtGui.QListWidget(self.tab_7)
        self.workChargesList.setObjectName(_fromUtf8("workChargesList"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.SpanningRole, self.workChargesList)
        self.wChargeSave = QtGui.QPushButton(self.tab_7)
        self.wChargeSave.setObjectName(_fromUtf8("wChargeSave"))
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.FieldRole, self.wChargeSave)
        self.wChargeTimes = QtGui.QSpinBox(self.tab_7)
        self.wChargeTimes.setObjectName(_fromUtf8("wChargeTimes"))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.FieldRole, self.wChargeTimes)
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.verticalLayout_5.addLayout(self.formLayout_9)
        self.gridLayout_12.addLayout(self.verticalLayout_5, 0, 2, 7, 1)
        self.label_8 = QtGui.QLabel(self.tab_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 1, 0, 1, 1)
        self.companyname = QtGui.QLineEdit(self.tab_7)
        self.companyname.setText(_fromUtf8(""))
        self.companyname.setObjectName(_fromUtf8("companyname"))
        self.gridLayout_12.addWidget(self.companyname, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_12.addWidget(self.label_15, 2, 0, 1, 1)
        self.loan = QtGui.QDoubleSpinBox(self.tab_7)
        self.loan.setDecimals(2)
        self.loan.setMaximum(99999999.99)
        self.loan.setProperty("value", 20.0)
        self.loan.setObjectName(_fromUtf8("loan"))
        self.gridLayout_12.addWidget(self.loan, 2, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_12.addWidget(self.label_24, 3, 0, 1, 1)
        self.perHours = QtGui.QDoubleSpinBox(self.tab_7)
        self.perHours.setDecimals(2)
        self.perHours.setMaximum(99999999.99)
        self.perHours.setProperty("value", 1.0)
        self.perHours.setObjectName(_fromUtf8("perHours"))
        self.gridLayout_12.addWidget(self.perHours, 3, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_7)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 4, 0, 1, 1)
        self.companydescription = QtGui.QTextEdit(self.tab_7)
        self.companydescription.setObjectName(_fromUtf8("companydescription"))
        self.gridLayout_12.addWidget(self.companydescription, 4, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.createCompany = QtGui.QPushButton(self.tab_7)
        self.createCompany.setObjectName(_fromUtf8("createCompany"))
        self.horizontalLayout_8.addWidget(self.createCompany)
        self.saveCompany = QtGui.QPushButton(self.tab_7)
        self.saveCompany.setObjectName(_fromUtf8("saveCompany"))
        self.horizontalLayout_8.addWidget(self.saveCompany)
        self.deleteCompany = QtGui.QPushButton(self.tab_7)
        self.deleteCompany.setObjectName(_fromUtf8("deleteCompany"))
        self.horizontalLayout_8.addWidget(self.deleteCompany)
        self.gridLayout_12.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.creditList = QtGui.QListWidget(self.tab)
        self.creditList.setObjectName(_fromUtf8("creditList"))
        self.gridLayout_11.addWidget(self.creditList, 0, 0, 4, 1)
        self.createCredit = QtGui.QPushButton(self.tab)
        self.createCredit.setObjectName(_fromUtf8("createCredit"))
        self.gridLayout_11.addWidget(self.createCredit, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gridLayout_11.addLayout(self.horizontalLayout_11, 0, 4, 1, 1)
        self.creditName = QtGui.QLineEdit(self.tab)
        self.creditName.setObjectName(_fromUtf8("creditName"))
        self.gridLayout_11.addWidget(self.creditName, 0, 3, 1, 1)
        self.creditValue = QtGui.QDoubleSpinBox(self.tab)
        self.creditValue.setDecimals(2)
        self.creditValue.setMaximum(99999.99)
        self.creditValue.setObjectName(_fromUtf8("creditValue"))
        self.gridLayout_11.addWidget(self.creditValue, 1, 3, 1, 1)
        self.creditDate = QtGui.QDateEdit(self.tab)
        self.creditDate.setCalendarPopup(True)
        self.creditDate.setObjectName(_fromUtf8("creditDate"))
        self.gridLayout_11.addWidget(self.creditDate, 2, 3, 1, 1)
        self.creditPayed = QtGui.QCheckBox(self.tab)
        self.creditPayed.setObjectName(_fromUtf8("creditPayed"))
        self.gridLayout_11.addWidget(self.creditPayed, 3, 3, 1, 1)
        self.creditActive = QtGui.QCheckBox(self.tab)
        self.creditActive.setChecked(True)
        self.creditActive.setObjectName(_fromUtf8("creditActive"))
        self.gridLayout_11.addWidget(self.creditActive, 3, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_11.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_11.addWidget(self.label_30, 0, 2, 1, 1)
        self.deleteCredit = QtGui.QPushButton(self.tab)
        self.deleteCredit.setObjectName(_fromUtf8("deleteCredit"))
        self.gridLayout_11.addWidget(self.deleteCredit, 4, 3, 1, 1)
        self.saveCredit = QtGui.QPushButton(self.tab)
        self.saveCredit.setObjectName(_fromUtf8("saveCredit"))
        self.gridLayout_11.addWidget(self.saveCredit, 4, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.plainTextEdit_3 = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit_3.setObjectName(_fromUtf8("plainTextEdit_3"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_3)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.loanDistractionName = QtGui.QLineEdit(self.tab_2)
        self.loanDistractionName.setObjectName(_fromUtf8("loanDistractionName"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.loanDistractionName)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.loanDistractionValue = QtGui.QDoubleSpinBox(self.tab_2)
        self.loanDistractionValue.setMaximum(9999.99)
        self.loanDistractionValue.setObjectName(_fromUtf8("loanDistractionValue"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.loanDistractionValue)
        self.loanDistractionMoney = QtGui.QCheckBox(self.tab_2)
        self.loanDistractionMoney.setObjectName(_fromUtf8("loanDistractionMoney"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.loanDistractionMoney)
        self.gridLayout_9.addLayout(self.formLayout_8, 0, 1, 1, 1)
        self.loanDistractionList = QtGui.QListWidget(self.tab_2)
        self.loanDistractionList.setObjectName(_fromUtf8("loanDistractionList"))
        self.gridLayout_9.addWidget(self.loanDistractionList, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.createLoanDistraction = QtGui.QPushButton(self.tab_2)
        self.createLoanDistraction.setObjectName(_fromUtf8("createLoanDistraction"))
        self.horizontalLayout_7.addWidget(self.createLoanDistraction)
        self.saveLoanDistraction = QtGui.QPushButton(self.tab_2)
        self.saveLoanDistraction.setObjectName(_fromUtf8("saveLoanDistraction"))
        self.horizontalLayout_7.addWidget(self.saveLoanDistraction)
        self.deleteLoanDistraction = QtGui.QPushButton(self.tab_2)
        self.deleteLoanDistraction.setObjectName(_fromUtf8("deleteLoanDistraction"))
        self.horizontalLayout_7.addWidget(self.deleteLoanDistraction)
        self.gridLayout_9.addLayout(self.horizontalLayout_7, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.verticalLayout.addWidget(self.plainTextEdit_4)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_42 = QtGui.QLabel(self.tab_3)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_10.addWidget(self.label_42, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.chargesName = QtGui.QLineEdit(self.tab_3)
        self.chargesName.setObjectName(_fromUtf8("chargesName"))
        self.horizontalLayout_9.addWidget(self.chargesName)
        self.gridLayout_10.addLayout(self.horizontalLayout_9, 1, 3, 1, 1)
        self.createCharge = QtGui.QPushButton(self.tab_3)
        self.createCharge.setObjectName(_fromUtf8("createCharge"))
        self.gridLayout_10.addWidget(self.createCharge, 3, 0, 1, 1)
        self.saveCharge = QtGui.QPushButton(self.tab_3)
        self.saveCharge.setObjectName(_fromUtf8("saveCharge"))
        self.gridLayout_10.addWidget(self.saveCharge, 3, 1, 1, 1)
        self.deleteCharge = QtGui.QPushButton(self.tab_3)
        self.deleteCharge.setObjectName(_fromUtf8("deleteCharge"))
        self.gridLayout_10.addWidget(self.deleteCharge, 3, 2, 1, 1)
        self.addChargeToJob = QtGui.QPushButton(self.tab_3)
        self.addChargeToJob.setObjectName(_fromUtf8("addChargeToJob"))
        self.gridLayout_10.addWidget(self.addChargeToJob, 3, 3, 1, 1)
        self.chargesValue = QtGui.QDoubleSpinBox(self.tab_3)
        self.chargesValue.setObjectName(_fromUtf8("chargesValue"))
        self.gridLayout_10.addWidget(self.chargesValue, 2, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_10.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 1, 2, 1, 1)
        self.chargesList = QtGui.QListWidget(self.tab_3)
        self.chargesList.setObjectName(_fromUtf8("chargesList"))
        self.gridLayout_10.addWidget(self.chargesList, 1, 0, 2, 2)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_13.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.tabWidget_2, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_40 = QtGui.QLabel(self.tab_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_4.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_8)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.mainTab.addTab(self.data, _fromUtf8(""))
        self.logic = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logic.sizePolicy().hasHeightForWidth())
        self.logic.setSizePolicy(sizePolicy)
        self.logic.setObjectName(_fromUtf8("logic"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.logic)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.viewTabs = QtGui.QTabWidget(self.logic)
        self.viewTabs.setObjectName(_fromUtf8("viewTabs"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.workCalendar = QtGui.QCalendarWidget(self.tab_4)
        self.workCalendar.setObjectName(_fromUtf8("workCalendar"))
        self.horizontalLayout_5.addWidget(self.workCalendar)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.filterAll = QtGui.QCheckBox(self.tab_4)
        self.filterAll.setChecked(True)
        self.filterAll.setObjectName(_fromUtf8("filterAll"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.filterAll)
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.infoSearch = QtGui.QLineEdit(self.tab_4)
        self.infoSearch.setText(_fromUtf8(""))
        self.infoSearch.setObjectName(_fromUtf8("infoSearch"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.infoSearch)
        self.filterCalendar = QtGui.QCheckBox(self.tab_4)
        self.filterCalendar.setChecked(True)
        self.filterCalendar.setObjectName(_fromUtf8("filterCalendar"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.filterCalendar)
        self.filterInactive = QtGui.QCheckBox(self.tab_4)
        self.filterInactive.setChecked(True)
        self.filterInactive.setObjectName(_fromUtf8("filterInactive"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.filterInactive)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.graphView = QtGui.QGraphicsView(self.tab_4)
        self.graphView.setObjectName(_fromUtf8("graphView"))
        self.horizontalLayout_5.addWidget(self.graphView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.infoExel = QtGui.QTableWidget(self.tab_4)
        self.infoExel.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.infoExel.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.infoExel.setColumnCount(9)
        self.infoExel.setObjectName(_fromUtf8("infoExel"))
        self.infoExel.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(8, item)
        self.infoExel.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_4.addWidget(self.infoExel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.infoExelCredits = QtGui.QTextEdit(self.tab_4)
        self.infoExelCredits.setReadOnly(True)
        self.infoExelCredits.setObjectName(_fromUtf8("infoExelCredits"))
        self.horizontalLayout_6.addWidget(self.infoExelCredits)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.amount = QtGui.QLCDNumber(self.tab_4)
        self.amount.setObjectName(_fromUtf8("amount"))
        self.horizontalLayout.addWidget(self.amount)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.viewTabs.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.companyViewSelect = QtGui.QComboBox(self.tab_5)
        self.companyViewSelect.setObjectName(_fromUtf8("companyViewSelect"))
        self.gridLayout.addWidget(self.companyViewSelect, 0, 0, 1, 1)
        self.companyViewCalendar = QtGui.QCalendarWidget(self.tab_5)
        self.companyViewCalendar.setObjectName(_fromUtf8("companyViewCalendar"))
        self.gridLayout.addWidget(self.companyViewCalendar, 2, 0, 1, 1)
        self.companyViewCalendarFilter = QtGui.QCheckBox(self.tab_5)
        self.companyViewCalendarFilter.setObjectName(_fromUtf8("companyViewCalendarFilter"))
        self.gridLayout.addWidget(self.companyViewCalendarFilter, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.companyViewText = QtGui.QTextEdit(self.tab_5)
        self.companyViewText.setReadOnly(True)
        self.companyViewText.setObjectName(_fromUtf8("companyViewText"))
        self.horizontalLayout_2.addWidget(self.companyViewText)
        self.viewTabs.addTab(self.tab_5, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.viewTabs)
        self.mainTab.addTab(self.logic, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pfSearchEnabled = QtGui.QCheckBox(self.tab_6)
        self.pfSearchEnabled.setChecked(True)
        self.pfSearchEnabled.setObjectName(_fromUtf8("pfSearchEnabled"))
        self.gridLayout_3.addWidget(self.pfSearchEnabled, 3, 4, 1, 1)
        self.pfSearch = QtGui.QLineEdit(self.tab_6)
        self.pfSearch.setObjectName(_fromUtf8("pfSearch"))
        self.gridLayout_3.addWidget(self.pfSearch, 0, 4, 1, 1)
        self.pfCalendarEnabled = QtGui.QCheckBox(self.tab_6)
        self.pfCalendarEnabled.setChecked(True)
        self.pfCalendarEnabled.setObjectName(_fromUtf8("pfCalendarEnabled"))
        self.gridLayout_3.addWidget(self.pfCalendarEnabled, 2, 4, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tab_6)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 1, 4, 1, 1)
        self.pfList = QtGui.QListWidget(self.tab_6)
        self.pfList.setObjectName(_fromUtf8("pfList"))
        self.gridLayout_3.addWidget(self.pfList, 0, 0, 4, 1)
        self.label_39 = QtGui.QLabel(self.tab_6)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 0, 3, 1, 1)
        self.pfCalendar = QtGui.QCalendarWidget(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pfCalendar.sizePolicy().hasHeightForWidth())
        self.pfCalendar.setSizePolicy(sizePolicy)
        self.pfCalendar.setObjectName(_fromUtf8("pfCalendar"))
        self.gridLayout_3.addWidget(self.pfCalendar, 1, 2, 3, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pfSave = QtGui.QPushButton(self.tab_6)
        self.pfSave.setObjectName(_fromUtf8("pfSave"))
        self.gridLayout_2.addWidget(self.pfSave, 10, 1, 1, 1)
        self.pfCreate = QtGui.QPushButton(self.tab_6)
        self.pfCreate.setObjectName(_fromUtf8("pfCreate"))
        self.gridLayout_2.addWidget(self.pfCreate, 8, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab_6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 1, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab_6)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 7, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_6)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_6)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 4, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 5, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_6)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 6, 1, 1, 1)
        self.pfName = QtGui.QLineEdit(self.tab_6)
        self.pfName.setObjectName(_fromUtf8("pfName"))
        self.gridLayout_2.addWidget(self.pfName, 0, 2, 1, 1)
        self.pfValue = QtGui.QDoubleSpinBox(self.tab_6)
        self.pfValue.setMaximum(9999999.99)
        self.pfValue.setObjectName(_fromUtf8("pfValue"))
        self.gridLayout_2.addWidget(self.pfValue, 1, 2, 1, 1)
        self.pfDate = QtGui.QDateEdit(self.tab_6)
        self.pfDate.setCalendarPopup(True)
        self.pfDate.setObjectName(_fromUtf8("pfDate"))
        self.gridLayout_2.addWidget(self.pfDate, 2, 2, 1, 1)
        self.pfRepeat = QtGui.QComboBox(self.tab_6)
        self.pfRepeat.setObjectName(_fromUtf8("pfRepeat"))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.pfRepeat.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pfRepeat, 4, 2, 1, 2)
        self.pfActive = QtGui.QCheckBox(self.tab_6)
        self.pfActive.setText(_fromUtf8(""))
        self.pfActive.setChecked(True)
        self.pfActive.setObjectName(_fromUtf8("pfActive"))
        self.gridLayout_2.addWidget(self.pfActive, 7, 2, 1, 1)
        self.pfRepeatTimes = QtGui.QSpinBox(self.tab_6)
        self.pfRepeatTimes.setMinimum(1)
        self.pfRepeatTimes.setObjectName(_fromUtf8("pfRepeatTimes"))
        self.gridLayout_2.addWidget(self.pfRepeatTimes, 5, 2, 1, 1)
        self.pfDelete = QtGui.QPushButton(self.tab_6)
        self.pfDelete.setObjectName(_fromUtf8("pfDelete"))
        self.gridLayout_2.addWidget(self.pfDelete, 8, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 3, 1, 1, 1)
        self.pfEndDate = QtGui.QDateEdit(self.tab_6)
        self.pfEndDate.setCalendarPopup(True)
        self.pfEndDate.setObjectName(_fromUtf8("pfEndDate"))
        self.gridLayout_2.addWidget(self.pfEndDate, 3, 2, 1, 1)
        self.pfPlusMinus = QtGui.QComboBox(self.tab_6)
        self.pfPlusMinus.setObjectName(_fromUtf8("pfPlusMinus"))
        self.pfPlusMinus.addItem(_fromUtf8(""))
        self.pfPlusMinus.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pfPlusMinus, 6, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.pfSummary = QtGui.QTextEdit(self.tab_6)
        self.pfSummary.setObjectName(_fromUtf8("pfSummary"))
        self.horizontalLayout_4.addWidget(self.pfSummary)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.mainTab.addTab(self.tab_6, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_6 = QtGui.QGridLayout(self.settings)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_23 = QtGui.QLabel(self.settings)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.configList = QtGui.QListWidget(self.settings)
        self.configList.setObjectName(_fromUtf8("configList"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.SpanningRole, self.configList)
        self.label_26 = QtGui.QLabel(self.settings)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.settings)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_27)
        self.configKey = QtGui.QLineEdit(self.settings)
        self.configKey.setObjectName(_fromUtf8("configKey"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.configKey)
        self.configValue = QtGui.QLineEdit(self.settings)
        self.configValue.setObjectName(_fromUtf8("configValue"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.configValue)
        self.createConfig = QtGui.QPushButton(self.settings)
        self.createConfig.setObjectName(_fromUtf8("createConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.LabelRole, self.createConfig)
        self.saveConfig = QtGui.QPushButton(self.settings)
        self.saveConfig.setObjectName(_fromUtf8("saveConfig"))
        self.formLayout_7.setWidget(6, QtGui.QFormLayout.FieldRole, self.saveConfig)
        self.deleteConfig = QtGui.QPushButton(self.settings)
        self.deleteConfig.setObjectName(_fromUtf8("deleteConfig"))
        self.formLayout_7.setWidget(7, QtGui.QFormLayout.FieldRole, self.deleteConfig)
        self.gridLayout_6.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.settings)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_6.addWidget(self.textEdit, 0, 1, 1, 1)
        self.mainTab.addTab(self.settings, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.mainTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.status = QtGui.QStatusBar(MainWindow)
        self.status.setObjectName(_fromUtf8("status"))
        MainWindow.setStatusBar(self.status)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.viewTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.mainTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Personal finances</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "Companys", None))
        self.label_2.setText(_translate("MainWindow", "Jobs", None))
        self.showInactive.setText(_translate("MainWindow", "Show Inactive", None))
        self.label_5.setText(_translate("MainWindow", "Jobname", None))
        self.label_6.setText(_translate("MainWindow", "Place", None))
        self.label_7.setText(_translate("MainWindow", "Baustellenleiter", None))
        self.label_13.setText(_translate("MainWindow", "Startdate", None))
        self.startdate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_14.setText(_translate("MainWindow", "Enddate", None))
        self.enddate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_9.setText(_translate("MainWindow", "Hours (per day)", None))
        self.label_12.setText(_translate("MainWindow", "Correction (allTime)", None))
        self.label_11.setText(_translate("MainWindow", "Weekenddays (per 7d)", None))
        self.jobComment.setPlainText(_translate("MainWindow", "Comments...", None))
        self.active.setText(_translate("MainWindow", "Active", None))
        self.deleteJob.setText(_translate("MainWindow", "Delete", None))
        self.saveJob.setText(_translate("MainWindow", "Save", None))
        self.createJob.setText(_translate("MainWindow", "Create", None))
        self.daysCalc.setText(_translate("MainWindow", "how many days..", None))
        self.hoursCalc.setText(_translate("MainWindow", "how many hours @all..", None))
        self.deleteWorkSpese.setText(_translate("MainWindow", "Delete", None))
        self.label_28.setText(_translate("MainWindow", "Workchargetime (0=daily)", None))
        self.wChargeSave.setText(_translate("MainWindow", "Save", None))
        self.label_29.setText(_translate("MainWindow", "Workcharge", None))
        self.label_8.setText(_translate("MainWindow", "Companyname", None))
        self.label_15.setText(_translate("MainWindow", "Loan", None))
        self.label_24.setText(_translate("MainWindow", "Per Hours", None))
        self.label_35.setText(_translate("MainWindow", "Comment / Details", None))
        self.createCompany.setText(_translate("MainWindow", "Create", None))
        self.saveCompany.setText(_translate("MainWindow", "Save", None))
        self.deleteCompany.setText(_translate("MainWindow", "Delete", None))
        self.createCredit.setText(_translate("MainWindow", "Create", None))
        self.creditDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.creditPayed.setText(_translate("MainWindow", "Payed", None))
        self.creditActive.setText(_translate("MainWindow", "Active", None))
        self.label_17.setText(_translate("MainWindow", "Date", None))
        self.label_16.setText(_translate("MainWindow", "Money", None))
        self.label_30.setText(_translate("MainWindow", "Name/Comment", None))
        self.deleteCredit.setText(_translate("MainWindow", "Delete", None))
        self.saveCredit.setText(_translate("MainWindow", "Save", None))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "In temporary companys you could take sometimes a part of the loan before month ends. Those are credits.", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Credits", None))
        self.label_21.setText(_translate("MainWindow", "Name", None))
        self.label_22.setText(_translate("MainWindow", "Value", None))
        self.loanDistractionMoney.setText(_translate("MainWindow", "on=money,off=percent", None))
        self.createLoanDistraction.setText(_translate("MainWindow", "Create", None))
        self.saveLoanDistraction.setText(_translate("MainWindow", "Save", None))
        self.deleteLoanDistraction.setText(_translate("MainWindow", "Delete", None))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "When there\'s go something substracted, as example insurances, taxes, etc", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Loan Distractions", None))
        self.label_42.setText(_translate("MainWindow", "Static Charges", None))
        self.createCharge.setText(_translate("MainWindow", "Create", None))
        self.saveCharge.setText(_translate("MainWindow", "Save", None))
        self.deleteCharge.setText(_translate("MainWindow", "Delete", None))
        self.addChargeToJob.setText(_translate("MainWindow", "Add to job", None))
        self.label_25.setText(_translate("MainWindow", "Money", None))
        self.label_18.setText(_translate("MainWindow", "Name", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "A charge is, when you have to pay your hotel or the food yourself and the company will pay it you back with the loan. \n"
"Add charges, which are defined by your company, to static charges. A static charge isn\'t used, until you add it to a job (right side).\n"
"When you \"add to job\" it, it becames a workcharge, means it is active for this job.", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Static Charges", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Companys and Jobs", None))
        self.label_40.setText(_translate("MainWindow", "Loan per year", None))
        self.label_41.setText(_translate("MainWindow", "Tax", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Taxes", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.data), _translate("MainWindow", "Data", None))
        self.mainTab.setTabToolTip(self.mainTab.indexOf(self.data), _translate("MainWindow", "Here u could put in ur stuff", None))
        self.filterAll.setText(_translate("MainWindow", " Filter @All", None))
        self.label_19.setText(_translate("MainWindow", "Search", None))
        self.filterCalendar.setText(_translate("MainWindow", "Filter Calendar", None))
        self.filterInactive.setText(_translate("MainWindow", "Show Inactive", None))
        self.infoExel.setSortingEnabled(True)
        item = self.infoExel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Companyname", None))
        item = self.infoExel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jobname", None))
        item = self.infoExel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Place", None))
        item = self.infoExel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Leader", None))
        item = self.infoExel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Loan", None))
        item = self.infoExel.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.infoExel.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Charges", None))
        item = self.infoExel.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Splits", None))
        item = self.infoExel.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Summe", None))
        self.label_10.setText(_translate("MainWindow", "Summe (gesammt)", None))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_4), _translate("MainWindow", "Overview for all", None))
        self.companyViewCalendarFilter.setText(_translate("MainWindow", "Calendarfilter", None))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_5), _translate("MainWindow", "Detailview Company", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.logic), _translate("MainWindow", "Analysis", None))
        self.pfSearchEnabled.setText(_translate("MainWindow", "  Search (at all)", None))
        self.pfCalendarEnabled.setText(_translate("MainWindow", "Filter Calendar", None))
        self.checkBox.setText(_translate("MainWindow", "Zeige Inaktive", None))
        self.label_39.setText(_translate("MainWindow", "Search", None))
        self.pfSave.setText(_translate("MainWindow", "Save", None))
        self.pfCreate.setText(_translate("MainWindow", "Create", None))
        self.label_31.setText(_translate("MainWindow", "Value", None))
        self.label_36.setText(_translate("MainWindow", "Active", None))
        self.label_33.setText(_translate("MainWindow", "Date", None))
        self.label_37.setText(_translate("MainWindow", "Repeat", None))
        self.label_38.setText(_translate("MainWindow", "Repeat Times", None))
        self.label_32.setText(_translate("MainWindow", "Name", None))
        self.label_34.setText(_translate("MainWindow", "Plus/Minus", None))
        self.pfDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.pfRepeat.setItemText(0, _translate("MainWindow", "None", None))
        self.pfRepeat.setItemText(1, _translate("MainWindow", "Daily", None))
        self.pfRepeat.setItemText(2, _translate("MainWindow", "Weekly", None))
        self.pfRepeat.setItemText(3, _translate("MainWindow", "Monthly", None))
        self.pfDelete.setText(_translate("MainWindow", "Delete", None))
        self.label_20.setText(_translate("MainWindow", "Enddate", None))
        self.pfEndDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.pfPlusMinus.setItemText(0, _translate("MainWindow", "+", None))
        self.pfPlusMinus.setItemText(1, _translate("MainWindow", "-", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_6), _translate("MainWindow", "Personal finances", None))
        self.label_23.setText(_translate("MainWindow", "Configs", None))
        self.label_26.setText(_translate("MainWindow", "Key", None))
        self.label_27.setText(_translate("MainWindow", "Value", None))
        self.createConfig.setText(_translate("MainWindow", "Create", None))
        self.saveConfig.setText(_translate("MainWindow", "Save", None))
        self.deleteConfig.setText(_translate("MainWindow", "Delete", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:18pt; text-decoration: underline;\">Avaible Config-Keys</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* lang / language = language - put the right filename (*.qm in your folder) there</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* singleview = 1 - enables singleView (experimental)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* encrypted : 1=CAST, 2=Blowfish, 3=DES3,4=ARC4,5=XOR,6=AES,7=ARC2 (you need to install pycrypto / python3-crypto @ *buntu). Put &quot;None&quot; as value for going back to cleartext. Encryption shouldn\'t need any restart.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Restart is needed after changes!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>", None))
        self.mainTab.setTabText(self.mainTab.indexOf(self.settings), _translate("MainWindow", "Settings", "en"))

