# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created: Thu Oct 23 15:47:59 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 783)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTab.sizePolicy().hasHeightForWidth())
        self.mainTab.setSizePolicy(sizePolicy)
        self.mainTab.setObjectName("mainTab")
        self.data = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setObjectName("data")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.data)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.data)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.companyList = QtWidgets.QListWidget(self.tab_7)
        self.companyList.setObjectName("companyList")
        self.gridLayout_7.addWidget(self.companyList, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_7)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.showInactive = QtWidgets.QCheckBox(self.tab_7)
        self.showInactive.setChecked(True)
        self.showInactive.setObjectName("showInactive")
        self.gridLayout_7.addWidget(self.showInactive, 0, 2, 1, 1)
        self.jobList = QtWidgets.QListWidget(self.tab_7)
        self.jobList.setObjectName("jobList")
        self.gridLayout_7.addWidget(self.jobList, 1, 1, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_7, 0, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_7)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.jobname = QtWidgets.QLineEdit(self.tab_7)
        self.jobname.setObjectName("jobname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.jobname)
        self.label_6 = QtWidgets.QLabel(self.tab_7)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.jobplace = QtWidgets.QLineEdit(self.tab_7)
        self.jobplace.setObjectName("jobplace")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jobplace)
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.baustellenleiter = QtWidgets.QLineEdit(self.tab_7)
        self.baustellenleiter.setObjectName("baustellenleiter")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.baustellenleiter)
        self.label_13 = QtWidgets.QLabel(self.tab_7)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.startdate = QtWidgets.QDateEdit(self.tab_7)
        self.startdate.setCalendarPopup(True)
        self.startdate.setObjectName("startdate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.startdate)
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.enddate = QtWidgets.QDateEdit(self.tab_7)
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName("enddate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.enddate)
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.hours = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.hours.setMaximum(24.0)
        self.hours.setProperty("value", 8.0)
        self.hours.setObjectName("hours")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hours)
        self.label_12 = QtWidgets.QLabel(self.tab_7)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.correctionHours = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.correctionHours.setObjectName("correctionHours")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.correctionHours)
        self.label_11 = QtWidgets.QLabel(self.tab_7)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.weekendDays = QtWidgets.QSpinBox(self.tab_7)
        self.weekendDays.setProperty("value", 2)
        self.weekendDays.setObjectName("weekendDays")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.weekendDays)
        self.jobComment = QtWidgets.QPlainTextEdit(self.tab_7)
        self.jobComment.setObjectName("jobComment")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.jobComment)
        self.active = QtWidgets.QCheckBox(self.tab_7)
        self.active.setChecked(True)
        self.active.setObjectName("active")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.active)
        self.deleteJob = QtWidgets.QPushButton(self.tab_7)
        self.deleteJob.setObjectName("deleteJob")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.deleteJob)
        self.saveJob = QtWidgets.QPushButton(self.tab_7)
        self.saveJob.setObjectName("saveJob")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.saveJob)
        self.createJob = QtWidgets.QPushButton(self.tab_7)
        self.createJob.setEnabled(False)
        self.createJob.setObjectName("createJob")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.createJob)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setObjectName("formLayout_9")
        self.daysCalc = QtWidgets.QLabel(self.tab_7)
        self.daysCalc.setObjectName("daysCalc")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.daysCalc)
        self.hoursCalc = QtWidgets.QLabel(self.tab_7)
        self.hoursCalc.setObjectName("hoursCalc")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hoursCalc)
        self.label_29 = QtWidgets.QLabel(self.tab_7)
        self.label_29.setObjectName("label_29")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.workChargesList = QtWidgets.QListWidget(self.tab_7)
        self.workChargesList.setObjectName("workChargesList")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.workChargesList)
        self.label_28 = QtWidgets.QLabel(self.tab_7)
        self.label_28.setObjectName("label_28")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.wChargeTimes = QtWidgets.QSpinBox(self.tab_7)
        self.wChargeTimes.setObjectName("wChargeTimes")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wChargeTimes)
        self.deleteWorkSpese = QtWidgets.QPushButton(self.tab_7)
        self.deleteWorkSpese.setObjectName("deleteWorkSpese")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.deleteWorkSpese)
        self.wChargeSave = QtWidgets.QPushButton(self.tab_7)
        self.wChargeSave.setObjectName("wChargeSave")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wChargeSave)
        self.verticalLayout_5.addLayout(self.formLayout_9)
        self.gridLayout_12.addLayout(self.verticalLayout_5, 0, 3, 8, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 1, 0, 1, 1)
        self.companyname = QtWidgets.QLineEdit(self.tab_7)
        self.companyname.setText("")
        self.companyname.setObjectName("companyname")
        self.gridLayout_12.addWidget(self.companyname, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_12.addWidget(self.label_15, 2, 0, 1, 1)
        self.loan = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.loan.setDecimals(2)
        self.loan.setMaximum(99999999.99)
        self.loan.setProperty("value", 20.0)
        self.loan.setObjectName("loan")
        self.gridLayout_12.addWidget(self.loan, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_12.addWidget(self.label_24, 3, 0, 1, 1)
        self.companydescription = QtWidgets.QTextEdit(self.tab_7)
        self.companydescription.setObjectName("companydescription")
        self.gridLayout_12.addWidget(self.companydescription, 4, 1, 1, 1)
        self.perHours = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.perHours.setDecimals(2)
        self.perHours.setMaximum(99999999.99)
        self.perHours.setProperty("value", 1.0)
        self.perHours.setObjectName("perHours")
        self.gridLayout_12.addWidget(self.perHours, 3, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.createCompany = QtWidgets.QPushButton(self.tab_7)
        self.createCompany.setObjectName("createCompany")
        self.horizontalLayout_8.addWidget(self.createCompany)
        self.saveCompany = QtWidgets.QPushButton(self.tab_7)
        self.saveCompany.setObjectName("saveCompany")
        self.horizontalLayout_8.addWidget(self.saveCompany)
        self.deleteCompany = QtWidgets.QPushButton(self.tab_7)
        self.deleteCompany.setObjectName("deleteCompany")
        self.horizontalLayout_8.addWidget(self.deleteCompany)
        self.gridLayout_12.addLayout(self.horizontalLayout_8, 5, 1, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.creditList = QtWidgets.QListWidget(self.tab)
        self.creditList.setObjectName("creditList")
        self.gridLayout_11.addWidget(self.creditList, 0, 0, 4, 1)
        self.createCredit = QtWidgets.QPushButton(self.tab)
        self.createCredit.setObjectName("createCredit")
        self.gridLayout_11.addWidget(self.createCredit, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_11.addLayout(self.horizontalLayout_11, 0, 4, 1, 1)
        self.creditName = QtWidgets.QLineEdit(self.tab)
        self.creditName.setObjectName("creditName")
        self.gridLayout_11.addWidget(self.creditName, 0, 3, 1, 1)
        self.creditValue = QtWidgets.QDoubleSpinBox(self.tab)
        self.creditValue.setDecimals(2)
        self.creditValue.setMaximum(99999.99)
        self.creditValue.setObjectName("creditValue")
        self.gridLayout_11.addWidget(self.creditValue, 1, 3, 1, 1)
        self.creditDate = QtWidgets.QDateEdit(self.tab)
        self.creditDate.setCalendarPopup(True)
        self.creditDate.setObjectName("creditDate")
        self.gridLayout_11.addWidget(self.creditDate, 2, 3, 1, 1)
        self.creditPayed = QtWidgets.QCheckBox(self.tab)
        self.creditPayed.setObjectName("creditPayed")
        self.gridLayout_11.addWidget(self.creditPayed, 3, 3, 1, 1)
        self.creditActive = QtWidgets.QCheckBox(self.tab)
        self.creditActive.setChecked(True)
        self.creditActive.setObjectName("creditActive")
        self.gridLayout_11.addWidget(self.creditActive, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 0, 2, 1, 1)
        self.deleteCredit = QtWidgets.QPushButton(self.tab)
        self.deleteCredit.setObjectName("deleteCredit")
        self.gridLayout_11.addWidget(self.deleteCredit, 4, 3, 1, 1)
        self.saveCredit = QtWidgets.QPushButton(self.tab)
        self.saveCredit.setObjectName("saveCredit")
        self.gridLayout_11.addWidget(self.saveCredit, 4, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_2.addWidget(self.plainTextEdit_3)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.loanDistractionName = QtWidgets.QLineEdit(self.tab_2)
        self.loanDistractionName.setObjectName("loanDistractionName")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loanDistractionName)
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.loanDistractionValue = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.loanDistractionValue.setMaximum(9999.99)
        self.loanDistractionValue.setObjectName("loanDistractionValue")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loanDistractionValue)
        self.loanDistractionMoney = QtWidgets.QCheckBox(self.tab_2)
        self.loanDistractionMoney.setObjectName("loanDistractionMoney")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loanDistractionMoney)
        self.gridLayout_9.addLayout(self.formLayout_8, 0, 1, 1, 1)
        self.loanDistractionList = QtWidgets.QListWidget(self.tab_2)
        self.loanDistractionList.setObjectName("loanDistractionList")
        self.gridLayout_9.addWidget(self.loanDistractionList, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.createLoanDistraction = QtWidgets.QPushButton(self.tab_2)
        self.createLoanDistraction.setObjectName("createLoanDistraction")
        self.horizontalLayout_7.addWidget(self.createLoanDistraction)
        self.saveLoanDistraction = QtWidgets.QPushButton(self.tab_2)
        self.saveLoanDistraction.setObjectName("saveLoanDistraction")
        self.horizontalLayout_7.addWidget(self.saveLoanDistraction)
        self.deleteLoanDistraction = QtWidgets.QPushButton(self.tab_2)
        self.deleteLoanDistraction.setObjectName("deleteLoanDistraction")
        self.horizontalLayout_7.addWidget(self.deleteLoanDistraction)
        self.gridLayout_9.addLayout(self.horizontalLayout_7, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.verticalLayout.addWidget(self.plainTextEdit_4)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_10.addWidget(self.label_42, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.chargesName = QtWidgets.QLineEdit(self.tab_3)
        self.chargesName.setObjectName("chargesName")
        self.horizontalLayout_9.addWidget(self.chargesName)
        self.gridLayout_10.addLayout(self.horizontalLayout_9, 1, 3, 1, 1)
        self.createCharge = QtWidgets.QPushButton(self.tab_3)
        self.createCharge.setObjectName("createCharge")
        self.gridLayout_10.addWidget(self.createCharge, 3, 0, 1, 1)
        self.saveCharge = QtWidgets.QPushButton(self.tab_3)
        self.saveCharge.setObjectName("saveCharge")
        self.gridLayout_10.addWidget(self.saveCharge, 3, 1, 1, 1)
        self.deleteCharge = QtWidgets.QPushButton(self.tab_3)
        self.deleteCharge.setObjectName("deleteCharge")
        self.gridLayout_10.addWidget(self.deleteCharge, 3, 2, 1, 1)
        self.addChargeToJob = QtWidgets.QPushButton(self.tab_3)
        self.addChargeToJob.setObjectName("addChargeToJob")
        self.gridLayout_10.addWidget(self.addChargeToJob, 3, 3, 1, 1)
        self.chargesValue = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.chargesValue.setObjectName("chargesValue")
        self.gridLayout_10.addWidget(self.chargesValue, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 2, 1, 1)
        self.chargesList = QtWidgets.QListWidget(self.tab_3)
        self.chargesList.setObjectName("chargesList")
        self.gridLayout_10.addWidget(self.chargesList, 1, 0, 2, 2)
        self.gridLayout_13.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_13.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout_12.addWidget(self.tabWidget_2, 7, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.tab_7)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_12.addWidget(self.line_2, 0, 2, 8, 1)
        self.line = QtWidgets.QFrame(self.tab_7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_12.addWidget(self.line, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.mainTab.addTab(self.data, "")
        self.logic = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logic.sizePolicy().hasHeightForWidth())
        self.logic.setSizePolicy(sizePolicy)
        self.logic.setObjectName("logic")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logic)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.viewTabs = QtWidgets.QTabWidget(self.logic)
        self.viewTabs.setObjectName("viewTabs")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.workCalendar = QtWidgets.QCalendarWidget(self.tab_4)
        self.workCalendar.setObjectName("workCalendar")
        self.horizontalLayout_5.addWidget(self.workCalendar)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.filterAll = QtWidgets.QCheckBox(self.tab_4)
        self.filterAll.setChecked(True)
        self.filterAll.setObjectName("filterAll")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.filterAll)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.infoSearch = QtWidgets.QLineEdit(self.tab_4)
        self.infoSearch.setText("")
        self.infoSearch.setObjectName("infoSearch")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.infoSearch)
        self.filterCalendar = QtWidgets.QCheckBox(self.tab_4)
        self.filterCalendar.setChecked(True)
        self.filterCalendar.setObjectName("filterCalendar")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.filterCalendar)
        self.filterInactive = QtWidgets.QCheckBox(self.tab_4)
        self.filterInactive.setChecked(True)
        self.filterInactive.setObjectName("filterInactive")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.filterInactive)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.graphView = QtWidgets.QGraphicsView(self.tab_4)
        self.graphView.setObjectName("graphView")
        self.horizontalLayout_5.addWidget(self.graphView)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.infoExel = QtWidgets.QTableWidget(self.tab_4)
        self.infoExel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.infoExel.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.infoExel.setColumnCount(9)
        self.infoExel.setObjectName("infoExel")
        self.infoExel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoExel.setHorizontalHeaderItem(8, item)
        self.infoExel.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_4.addWidget(self.infoExel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.infoExelCredits = QtWidgets.QTextEdit(self.tab_4)
        self.infoExelCredits.setReadOnly(True)
        self.infoExelCredits.setObjectName("infoExelCredits")
        self.horizontalLayout_6.addWidget(self.infoExelCredits)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.amount = QtWidgets.QLCDNumber(self.tab_4)
        self.amount.setObjectName("amount")
        self.horizontalLayout.addWidget(self.amount)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.viewTabs.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.companyViewSelect = QtWidgets.QComboBox(self.tab_5)
        self.companyViewSelect.setObjectName("companyViewSelect")
        self.gridLayout.addWidget(self.companyViewSelect, 0, 0, 1, 1)
        self.companyViewCalendar = QtWidgets.QCalendarWidget(self.tab_5)
        self.companyViewCalendar.setObjectName("companyViewCalendar")
        self.gridLayout.addWidget(self.companyViewCalendar, 2, 0, 1, 1)
        self.companyViewCalendarFilter = QtWidgets.QCheckBox(self.tab_5)
        self.companyViewCalendarFilter.setObjectName("companyViewCalendarFilter")
        self.gridLayout.addWidget(self.companyViewCalendarFilter, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.companyViewText = QtWidgets.QTextEdit(self.tab_5)
        self.companyViewText.setReadOnly(True)
        self.companyViewText.setObjectName("companyViewText")
        self.horizontalLayout_2.addWidget(self.companyViewText)
        self.viewTabs.addTab(self.tab_5, "")
        self.horizontalLayout_3.addWidget(self.viewTabs)
        self.mainTab.addTab(self.logic, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pfSearchEnabled = QtWidgets.QCheckBox(self.tab_6)
        self.pfSearchEnabled.setChecked(True)
        self.pfSearchEnabled.setObjectName("pfSearchEnabled")
        self.gridLayout_3.addWidget(self.pfSearchEnabled, 3, 4, 1, 1)
        self.pfSearch = QtWidgets.QLineEdit(self.tab_6)
        self.pfSearch.setObjectName("pfSearch")
        self.gridLayout_3.addWidget(self.pfSearch, 0, 4, 1, 1)
        self.pfCalendarEnabled = QtWidgets.QCheckBox(self.tab_6)
        self.pfCalendarEnabled.setChecked(True)
        self.pfCalendarEnabled.setObjectName("pfCalendarEnabled")
        self.gridLayout_3.addWidget(self.pfCalendarEnabled, 2, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 1, 4, 1, 1)
        self.pfList = QtWidgets.QListWidget(self.tab_6)
        self.pfList.setObjectName("pfList")
        self.gridLayout_3.addWidget(self.pfList, 0, 0, 4, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 3, 1, 1)
        self.pfCalendar = QtWidgets.QCalendarWidget(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pfCalendar.sizePolicy().hasHeightForWidth())
        self.pfCalendar.setSizePolicy(sizePolicy)
        self.pfCalendar.setObjectName("pfCalendar")
        self.gridLayout_3.addWidget(self.pfCalendar, 1, 2, 3, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pfSave = QtWidgets.QPushButton(self.tab_6)
        self.pfSave.setObjectName("pfSave")
        self.gridLayout_2.addWidget(self.pfSave, 10, 1, 1, 1)
        self.pfCreate = QtWidgets.QPushButton(self.tab_6)
        self.pfCreate.setObjectName("pfCreate")
        self.gridLayout_2.addWidget(self.pfCreate, 8, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 7, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 4, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 5, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 6, 1, 1, 1)
        self.pfName = QtWidgets.QLineEdit(self.tab_6)
        self.pfName.setObjectName("pfName")
        self.gridLayout_2.addWidget(self.pfName, 0, 2, 1, 1)
        self.pfValue = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.pfValue.setMaximum(9999999.99)
        self.pfValue.setObjectName("pfValue")
        self.gridLayout_2.addWidget(self.pfValue, 1, 2, 1, 1)
        self.pfDate = QtWidgets.QDateEdit(self.tab_6)
        self.pfDate.setCalendarPopup(True)
        self.pfDate.setObjectName("pfDate")
        self.gridLayout_2.addWidget(self.pfDate, 2, 2, 1, 1)
        self.pfRepeat = QtWidgets.QComboBox(self.tab_6)
        self.pfRepeat.setObjectName("pfRepeat")
        self.pfRepeat.addItem("")
        self.pfRepeat.addItem("")
        self.pfRepeat.addItem("")
        self.pfRepeat.addItem("")
        self.gridLayout_2.addWidget(self.pfRepeat, 4, 2, 1, 2)
        self.pfActive = QtWidgets.QCheckBox(self.tab_6)
        self.pfActive.setText("")
        self.pfActive.setChecked(True)
        self.pfActive.setObjectName("pfActive")
        self.gridLayout_2.addWidget(self.pfActive, 7, 2, 1, 1)
        self.pfRepeatTimes = QtWidgets.QSpinBox(self.tab_6)
        self.pfRepeatTimes.setMinimum(1)
        self.pfRepeatTimes.setObjectName("pfRepeatTimes")
        self.gridLayout_2.addWidget(self.pfRepeatTimes, 5, 2, 1, 1)
        self.pfDelete = QtWidgets.QPushButton(self.tab_6)
        self.pfDelete.setObjectName("pfDelete")
        self.gridLayout_2.addWidget(self.pfDelete, 8, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 1, 1, 1)
        self.pfEndDate = QtWidgets.QDateEdit(self.tab_6)
        self.pfEndDate.setCalendarPopup(True)
        self.pfEndDate.setObjectName("pfEndDate")
        self.gridLayout_2.addWidget(self.pfEndDate, 3, 2, 1, 1)
        self.pfPlusMinus = QtWidgets.QComboBox(self.tab_6)
        self.pfPlusMinus.setObjectName("pfPlusMinus")
        self.pfPlusMinus.addItem("")
        self.pfPlusMinus.addItem("")
        self.gridLayout_2.addWidget(self.pfPlusMinus, 6, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.pfSummary = QtWidgets.QTextEdit(self.tab_6)
        self.pfSummary.setObjectName("pfSummary")
        self.horizontalLayout_4.addWidget(self.pfSummary)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.mainTab.addTab(self.tab_6, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_23 = QtWidgets.QLabel(self.settings)
        self.label_23.setObjectName("label_23")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.configList = QtWidgets.QListWidget(self.settings)
        self.configList.setObjectName("configList")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.configList)
        self.label_26 = QtWidgets.QLabel(self.settings)
        self.label_26.setObjectName("label_26")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.settings)
        self.label_27.setObjectName("label_27")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.configKey = QtWidgets.QLineEdit(self.settings)
        self.configKey.setObjectName("configKey")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.configKey)
        self.configValue = QtWidgets.QLineEdit(self.settings)
        self.configValue.setObjectName("configValue")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.configValue)
        self.createConfig = QtWidgets.QPushButton(self.settings)
        self.createConfig.setObjectName("createConfig")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.createConfig)
        self.saveConfig = QtWidgets.QPushButton(self.settings)
        self.saveConfig.setObjectName("saveConfig")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.saveConfig)
        self.deleteConfig = QtWidgets.QPushButton(self.settings)
        self.deleteConfig.setObjectName("deleteConfig")
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.deleteConfig)
        self.gridLayout_6.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.settings)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 0, 1, 1, 1)
        self.mainTab.addTab(self.settings, "")
        self.gridLayout_5.addWidget(self.mainTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.status = QtWidgets.QStatusBar(MainWindow)
        self.status.setObjectName("status")
        MainWindow.setStatusBar(self.status)

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.viewTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTab.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Personal finances</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Companys"))
        self.label_2.setText(_translate("MainWindow", "Jobs"))
        self.showInactive.setText(_translate("MainWindow", "Show Inactive"))
        self.label_5.setText(_translate("MainWindow", "Jobname"))
        self.label_6.setText(_translate("MainWindow", "Place"))
        self.label_7.setText(_translate("MainWindow", "Baustellenleiter"))
        self.label_13.setText(_translate("MainWindow", "Startdate"))
        self.startdate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_14.setText(_translate("MainWindow", "Enddate"))
        self.enddate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_9.setText(_translate("MainWindow", "Hours (per day)"))
        self.label_12.setText(_translate("MainWindow", "Correction (allTime)"))
        self.label_11.setText(_translate("MainWindow", "Weekenddays (per 7d)"))
        self.jobComment.setPlainText(_translate("MainWindow", "Comments..."))
        self.active.setText(_translate("MainWindow", "Active"))
        self.deleteJob.setText(_translate("MainWindow", "Delete"))
        self.saveJob.setText(_translate("MainWindow", "Save"))
        self.createJob.setText(_translate("MainWindow", "Create"))
        self.daysCalc.setText(_translate("MainWindow", "how many days.."))
        self.hoursCalc.setText(_translate("MainWindow", "how many hours @all.."))
        self.label_29.setText(_translate("MainWindow", "Workcharge"))
        self.label_28.setText(_translate("MainWindow", "Workchargetime (0=daily)"))
        self.deleteWorkSpese.setText(_translate("MainWindow", "Delete"))
        self.wChargeSave.setText(_translate("MainWindow", "Save"))
        self.label_8.setText(_translate("MainWindow", "Companyname"))
        self.label_15.setText(_translate("MainWindow", "Loan"))
        self.label_24.setText(_translate("MainWindow", "Per Hours"))
        self.label_35.setText(_translate("MainWindow", "Comment / Details"))
        self.createCompany.setText(_translate("MainWindow", "Create"))
        self.saveCompany.setText(_translate("MainWindow", "Save"))
        self.deleteCompany.setText(_translate("MainWindow", "Delete"))
        self.createCredit.setText(_translate("MainWindow", "Create"))
        self.creditDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.creditPayed.setText(_translate("MainWindow", "Payed"))
        self.creditActive.setText(_translate("MainWindow", "Active"))
        self.label_17.setText(_translate("MainWindow", "Date"))
        self.label_16.setText(_translate("MainWindow", "Money"))
        self.label_30.setText(_translate("MainWindow", "Name/Comment"))
        self.deleteCredit.setText(_translate("MainWindow", "Delete"))
        self.saveCredit.setText(_translate("MainWindow", "Save"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "In temporary companys you could take sometimes a part of the loan before month ends. Those are credits."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Credits"))
        self.label_21.setText(_translate("MainWindow", "Name"))
        self.label_22.setText(_translate("MainWindow", "Value"))
        self.loanDistractionMoney.setText(_translate("MainWindow", "on=money,off=percent"))
        self.createLoanDistraction.setText(_translate("MainWindow", "Create"))
        self.saveLoanDistraction.setText(_translate("MainWindow", "Save"))
        self.deleteLoanDistraction.setText(_translate("MainWindow", "Delete"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "When there\'s go something substracted, as example insurances, taxes, etc"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Loan Distractions"))
        self.label_42.setText(_translate("MainWindow", "Static Charges"))
        self.createCharge.setText(_translate("MainWindow", "Create"))
        self.saveCharge.setText(_translate("MainWindow", "Save"))
        self.deleteCharge.setText(_translate("MainWindow", "Delete"))
        self.addChargeToJob.setText(_translate("MainWindow", "Add to job"))
        self.label_25.setText(_translate("MainWindow", "Money"))
        self.label_18.setText(_translate("MainWindow", "Name"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "A charge is, when you have to pay your hotel or the food yourself and the company will pay it you back with the loan. \n"
"Add charges, which are defined by your company, to static charges. A static charge isn\'t used, until you add it to a job (right side).\n"
"When you \"add to job\" it, it becames a workcharge, means it is active for this job."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Static Charges"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Companys and Jobs"))
        self.label_40.setText(_translate("MainWindow", "Loan per year"))
        self.label_41.setText(_translate("MainWindow", "Tax"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Taxes"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.data), _translate("MainWindow", "Data"))
        self.mainTab.setTabToolTip(self.mainTab.indexOf(self.data), _translate("MainWindow", "Here u could put in ur stuff"))
        self.filterAll.setText(_translate("MainWindow", " Filter @All"))
        self.label_19.setText(_translate("MainWindow", "Search"))
        self.filterCalendar.setText(_translate("MainWindow", "Filter Calendar"))
        self.filterInactive.setText(_translate("MainWindow", "Show Inactive"))
        self.infoExel.setSortingEnabled(True)
        item = self.infoExel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Companyname"))
        item = self.infoExel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Jobname"))
        item = self.infoExel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Place"))
        item = self.infoExel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Leader"))
        item = self.infoExel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Loan"))
        item = self.infoExel.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Time"))
        item = self.infoExel.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Charges"))
        item = self.infoExel.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Splits"))
        item = self.infoExel.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Summe"))
        self.label_10.setText(_translate("MainWindow", "Summe (gesammt)"))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_4), _translate("MainWindow", "Overview for all"))
        self.companyViewCalendarFilter.setText(_translate("MainWindow", "Calendarfilter"))
        self.viewTabs.setTabText(self.viewTabs.indexOf(self.tab_5), _translate("MainWindow", "Detailview Company"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.logic), _translate("MainWindow", "Analysis"))
        self.pfSearchEnabled.setText(_translate("MainWindow", "  Search (at all)"))
        self.pfCalendarEnabled.setText(_translate("MainWindow", "Filter Calendar"))
        self.checkBox.setText(_translate("MainWindow", "Zeige Inaktive"))
        self.label_39.setText(_translate("MainWindow", "Search"))
        self.pfSave.setText(_translate("MainWindow", "Save"))
        self.pfCreate.setText(_translate("MainWindow", "Create"))
        self.label_31.setText(_translate("MainWindow", "Value"))
        self.label_36.setText(_translate("MainWindow", "Active"))
        self.label_33.setText(_translate("MainWindow", "Date"))
        self.label_37.setText(_translate("MainWindow", "Repeat"))
        self.label_38.setText(_translate("MainWindow", "Repeat Times"))
        self.label_32.setText(_translate("MainWindow", "Name"))
        self.label_34.setText(_translate("MainWindow", "Plus/Minus"))
        self.pfDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.pfRepeat.setItemText(0, _translate("MainWindow", "None"))
        self.pfRepeat.setItemText(1, _translate("MainWindow", "Daily"))
        self.pfRepeat.setItemText(2, _translate("MainWindow", "Weekly"))
        self.pfRepeat.setItemText(3, _translate("MainWindow", "Monthly"))
        self.pfDelete.setText(_translate("MainWindow", "Delete"))
        self.label_20.setText(_translate("MainWindow", "Enddate"))
        self.pfEndDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.pfPlusMinus.setItemText(0, _translate("MainWindow", "+"))
        self.pfPlusMinus.setItemText(1, _translate("MainWindow", "-"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tab_6), _translate("MainWindow", "Personal finances"))
        self.label_23.setText(_translate("MainWindow", "Configs"))
        self.label_26.setText(_translate("MainWindow", "Key"))
        self.label_27.setText(_translate("MainWindow", "Value"))
        self.createConfig.setText(_translate("MainWindow", "Create"))
        self.saveConfig.setText(_translate("MainWindow", "Save"))
        self.deleteConfig.setText(_translate("MainWindow", "Delete"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Oxygen-Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:18pt; text-decoration: underline;\">Avaible Config-Keys</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* lang / language = language - put the right filename (*.qm in your folder) there</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* singleview = 1 - enables singleView (experimental)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">* encrypted : 1=CAST, 2=Blowfish, 3=DES3,4=ARC4,5=XOR,6=AES,7=ARC2 (you need to install pycrypto / python3-crypto @ *buntu). Put &quot;None&quot; as value for going back to cleartext. Encryption shouldn\'t need any restart.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:9pt;\">Restart is needed after changes!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.settings), _translate("MainWindow", "Settings", "en"))

